### ISSUE TITLE
Create functions to get width and gutter

### ISSUE THREAD

**Issue by AleksejDix** [peterramsing/lost#120]
It would be nice if it were possible to get global gutter variable.

``` css
.foo{
 padding: $lost-gutter;
}
```

**Comment by corysimmons** [comment]
Agreed. It would also be nice to get the size of a column.

I need to add functions for these.

**Comment by corysimmons** [comment]
In the meantime, maybe just set a variable with CSS or your preprocessor that mirrors your gutter's size. Since it's a fixed number it shouldn't deviate.

**Comment by AleksejDix** [comment]
yeah i did it allready. i'm currently rebuilding my personal website. would be fast as hell

**Comment by kogakure** [comment]
This helper would be more than useful. I tried to rebuild my grid (build with Singularity.gs), but one thing didn’t work with Lost: I have an `lost-column: 8/12 0`, `lost-offset: -2/12`. But some of my images should *break* out of the grid. I could set the width with `lost-column: 14/12 0` but couldn't pull the image negative out of it’s parent container.

**Comment by corysimmons** [comment]
Would love some help on this if anyone wants to tackle it!

**Comment by peterramsing** [comment]
Additional request from @perkola in #189. "merged" into this issue

---

Given that the gutter is declared with `@lost gutter 20px` or left at the default value, how can it be accessed in styling? For example:

```
.row {
    padding: $gutter;
}
```

does not work.

**Comment by corysimmons** [comment]
You could assign the value of the gutter to a variable, then you could make it so PostCSS went over all the selectors and `property: values` in the stylesheet. If it finds any instances of `$lost-gutter` (or whatever you want) then replace `$lost-gutter` with the gutter variable's value.

So someone's code might look like this:

``` css
@lost gutter 20px;

.foo {
  padding: $lost-gutter;
}
```

**Comment by peterramsing** [comment]
@corysimmons I like that. :+1: 

I'm curious if that would take a performance hit. Might be worth doing some testing.

**Comment by corysimmons** [comment]
Yeah, and there's always the question of what gutter do you take? The global one, or do you take a locally defined one? For instance, if I have a column with a special gutter on it, I probably want the padding on the inside to match it's special gutter. Gets a bit tricky. :^)

**Comment by AleksejDix** [comment]
Well i always wanted to have a global gutter variable. :dancer: i think local is too much.

**Comment by LostSenSS** [comment]
What about functions like this:

``` css
width: lost-column(5/12);
margin-left: lost-column(1/12);
```

Susy has [similar span function](http://susydocs.oddbird.net/en/latest/toolkit/#span-function). It's very useful. 
Is it possible?

**Comment by peterramsing** [comment]
@LostSenSS Hmm. I do like that aspect of Susy.

This is something that is still getting scoped out.

**Comment by peterramsing** [comment]
Looking at this again for a possible candidate for version 8, I think what I might do to start off is to simply add a variable like you suggested and replace it with the global gutter.

I think I can also offer it locally within a selector.

**Comment by peterramsing** [comment]
I have some working code where a `$lost-gutter` variable is replaced by the global gutter. I'm thinking through what it might look like if a declaration might also have a local gutter... more to ponder.

**Comment by peterramsing** [comment]
Closing for #346
