### ISSUE TITLE
Cycle in example

### ISSUE THREAD

**Issue by Manaus** [peterramsing/lost#155]
Hi, 
I cannot get the logic behind cycle = 0 in the [given example](https://github.com/corysimmons/lost#controlling-cycle), in the `quarter` and `half` classes. If I do not set a cycle value, I get the first quarter div with a right margin, but not the half div. If I set cycle to `0`, I get the first quarter and first half with the margin, but not the second quarter. 

Thanks

**Comment by peterramsing** [comment]
A little late replying, but does this still need addressing @Manaus? If so, could you share the code in question?

Thanks,
Peter
