### ISSUE TITLE
Comparison with Semantic-UI Grid

### ISSUE THREAD

**Issue by tunnckoCore** [peterramsing/lost#157]
You can just use the single module

https://cdn.rawgit.com/semantic-org/ui-grid/master/grid.css
https://github.com/semantic-org/ui-grid
http://semantic-ui.com/collections/grid.html

I think it's pretty better than all them all, only not sure what's the position compared to Lost.

**Comment by corysimmons** [comment]
Give me some time to get familiar with Semantic UI's grid. Big fan of Semantic UI. Actually tried to do the [theming stuff](https://github.com/corysimmons/switch) before.

**Comment by corysimmons** [comment]
It's a negative margin flexbox grid.

Not a super bad choice but it screws up adding background color to rows.

http://imgur.com/a/Lo7j1

Also, here are my thoughts on those types of grids https://www.reddit.com/r/web_design/comments/1llnqw/what_are_your_thoughts_on_paddingbased_framework/

**Comment by corysimmons** [comment]
It also specifies the name of the columns meaning it is always stuck to 16 columns (which is a bad number to pick as it doesn't factor down nicely like 12 or 24 but whatever).

```html
<div class="ui grid">
  <div class="eight wide column"></div>
  <div class="eight wide column"></div>
  <div class="ten wide column"></div>
  <div class="six wide column"></div>
  <div class="four wide column"></div>
  <div class="twelve wide column"></div>
  <div class="two wide column"></div>
  <div class="fourteen wide column"></div>
  <div class="sixteen wide column"></div>
</div>
```

Lost lets you set the background to rows that will actually line up and you can use any fraction of a size you can think up for your grid - not just 16 columns.

**Comment by corysimmons** [comment]
It's really not bad. I think it just serves a different audience.

I'll also be the first to admit it reads really, really, well. "stackable four column grid".

**Comment by tunnckoCore** [comment]
Thanks for the comments! Yea, i understand the idea behind the Lost - grid composition in the user hands, as i can say.
And yea Semantic-UI is absolute awesome chunk of intelligence! Even before he got v1, even before v0.11.9, it was awesome. More awesome than all others - Bootstrap, Skeleton, YAML4, Foundation and etc. Checkout the legacy `v0.x.x` website - it also was awesome.

And yea, Lost gives freedom. Great job!

> Actually tried to do the theming stuff before.

I'll check it! :)

**Comment by corysimmons** [comment]
Happy to accept a PR for this.

**Comment by peterramsing** [comment]
Closing: see #198 for continued conversation
