### ISSUE TITLE
Error in the variable without leading zero

### ISSUE THREAD

**Issue by brokerUA** [peterramsing/lost#173]
.class { lost-column: 1/2 0 **.1rem**; } — error (it takes the default value)

.class { lost-column: 1/2 0 **0.1rem**; } — good

**Comment by corysimmons** [comment]
Hm.. This might be an issue with PostCSS.

@ai ping

**Comment by peterramsing** [comment]
This looks to be more of a syntax issue, not anything that needs to be changed.
