### ISSUE TITLE
Examples of ratio-based, asymmetrical grids being created by Lost?

### ISSUE THREAD

**Issue by lozandier** [peterramsing/lost#177]
For content-first layouts, it's very common for asymmetrical grids to be made leveraging ratios such as the golden ratio. 

Can Lost's readme provide examples of this being done in Lost? 

Grid ratios that support grids such as Susy & SingularityGS typically have formats such as `1 3.618` to enable authors to leverage the third & first note of the golden ratio.

**Comment by peterramsing** [comment]
This is certainly something worth looking into. @lozandier Could you share some more thoughts on how you might want this implemented?

**Comment by peterramsing** [comment]
This issue is getting a bit stale. If you'd like to bring this issue back up please feel free to reach out.
