### ISSUE TITLE
Grid example

### ISSUE THREAD

**Issue by mike1a2a3a** [peterramsing/lost#185]
I'd like to implement a grid that looks like this:
![](http://i.imgur.com/1B2Mp3T.png)

I'm having trouble figuring out how I can implement this, in particular the fixed-width columns and the "remaining space" column.  Let me know if this is possible with lost grid, thanks.

**Comment by ghost** [comment]
It's been almost a month, does anyone know if creating a fixed-width column in lost-grid is possible, or are columns always fractional-based (1/2, 1/3, 2/5 etc)? Thanks @corysimmons

**Comment by peterramsing** [comment]
Sorry for the delay. The quick answer for this might be to use a combination of Lost and vanilla CSS.

See #142

**Comment by corysimmons** [comment]
This kind of layout actually looks like it'd be better suited for pure flexbox.

http://codepen.io/corysimmons/pen/yeVgLY?editors=110
