### ISSUE TITLE
Asymmetric Waffle Grids

### ISSUE THREAD

**Issue by lukasziegler** [peterramsing/lost#187]
Hi @corysimmons,

does lost grid support asymmetric waffle grids? The aspired use case is to have one card double the size of all other cards. 

````
|--------|----|----|
|        | 2  | 3  |
|   1    |----|----|
|        | 4  | 5  |
|--------|----|----|
```

I first used an approach combining `lost-column` and `lost-row`, which is apparently not supported:

Jade
```
section.layout
  div.card.card-large 1
  div.card 2
  div.card 3
  div.card 4
  div.card 5
```

Stylus 
```
.layout
  lost-center 800px
  lost-utility edit
  .card
    lost-column 1/4
    lost-row 1/2
  .card-large
    lost-column 1/2
    lost-row 1
```

With `lost-waffle` it works better (the sizing is correct), unfortunately the `cycle` isn't calculated correctly anymore. The calculation of `nth-child(n)` and `nth-child(n+1)` would need to be adjusted.

Jade
```
section.layout-waffle
  div.card-large 1
  div.card 2
  div.card 3
  div.card 4
  div.card 5
```

Stylus
```
.layout-waffle
  lost-center 800px
  lost-utility edit
  .card
    lost-waffle 1/4 3
  .card-large
    lost-waffle 1/2
```

Did I misunderstand the way to use lost-grid for this scenario or does lost grid currently not support asymmetric waffle grids?

As a fallback-scenario I created asymmetric waffle grids with a nested grid structure (having two 1/2 width columns and nesting cards 2, 3, 4 and 5 in the right 1/2 width column). That works for sure, but for the finest grid it would be pretty neat to also support the mentioned scenario :)

Thanks,
Lukas

**Comment by peterramsing** [comment]
Hey @lukasziegler : I think you've touched on some functionality of the cycle that isn't there. I want to do some work on defining exactly what the cycle feature should/can do for future versions. It looks like you've got a solution that works and would love your input on future definitions of the cycle feature. Is it okay if I close this and follow up in a larger discussion about cycle and how it should be used in lost?

**Comment by corysimmons** [comment]
Does this work? http://codepen.io/corysimmons/pen/ZQBBvE?editors=110

I can't think of a way to alter waffle to accept larger blocks and such on the fly. I'd be cool if you could though.

**Comment by lukasziegler** [comment]
Good idea @peterramsing. Discussing the functionality of asymmetric waffle grids in a larger discussion round would be great. 

@corysimmons That's how I currently implemented it, but it's not exactly what I would have expected. Thanks for your input. I'll be pleased to join the discussions.
