### ISSUE TITLE
Descriptions on Example Page

### ISSUE THREAD

**Issue by moshemo** [peterramsing/lost#191]
Your example page is very nice (i.e., this page:  http://corysimmons.github.io/lost/).  

However, it would be even better if you could add in the css styles you used in each example (along with or instead of the numbers and lorem ipsum text).  That way it would be easier for us to figure out how to reproduce the examples.

Either way, thanks for lost -- it is extremely helpful.

**Comment by peterramsing** [comment]
I've been working on a version of the README.md that has the "lost-syntax" with the "processed-css" following. I'm not sure if it's of any help for what you're asking but here's a gist to the current WIP I have.

https://gist.github.com/peterramsing/b6b420ac5a39dcaaecf1

Maybe in the next few weeks I can get around to working on the wiki with this in a lot more readable form.

**Comment by corysimmons** [comment]
Ah that's cool Peter. :+1: 

If you want to submit a PR for the updated README I'll merge.

If you do, would you mind adding `style="background: none !important;"` to those checkmarks on the comparison table?

**Comment by peterramsing** [comment]
Pull Request coming in– I tried to add the inline style for the images but GitHub stripped it out. Any problem for another night.

**Comment by peterramsing** [comment]
Bugger-this got added to my previous PR. I can branch from the previous version if you'd like this pulled into a separate PR.

**Comment by peterramsing** [comment]
See #179

**Comment by corysimmons** [comment]
Nah, don't get too caught up in being a GitHub perfectionist or you'll never get anything done. Just try to adhere to semver best you can and remember you're working for free. :^)

**Comment by peterramsing** [comment]
@corysimmons Thanks! :+1:
