### ISSUE TITLE
Error in Better than X comparative table

### ISSUE THREAD

**Issue by iRouge** [peterramsing/lost#198]
The table claims _Lost_ to be the only one that offers flexbox grids. As of today, new versions of Bootstrap (4 alpha: http://v4-alpha.getbootstrap.com/getting-started/flexbox/) and Foundation (6: http://foundation.zurb.com/sites/docs/flex-grid.html) now have flexbox grids. 

In my opinion, The Bootstrap version is still ill-implemented but that's another story.

**Comment by peterramsing** [comment]
I'll be looking into this. With how fast all these grids are moving having a table up to date is tough. To properly express this in the current chart would be hard as Bootstrap is in Alpha-so does that count?

@iRouge Do you think this could be better served as a third-party grid comparison table? This comparison table isn't just helpful for Lost.

**Comment by peterramsing** [comment]
Also-I'm not going to make any immediate changes as I think I'm going to do some larger changes to the README and want to have them planned out before proceeding. :smile:

**Comment by corysimmons** [comment]
> Do you think this could be better served as a third-party grid comparison table? This comparison table isn't just helpful for Lost.

I would love to see someone create an open source project that was simply a gh-pages site with a comparison table of the various grids on there...

We could transfer it out of this README and multiple people could help maintain it. It would become an incredibly popular resource for anyone looking into various grids.

Funnily enough, the grid used to make that table of data would probably work best as simply flexbox since you'd be adding/removing columns/rows all the time. :^)

**Comment by peterramsing** [comment]
@corysimmons You're reading my mind. I think I need to take another vacation just to get some of this all done. :smile:

**Comment by corysimmons** [comment]
Foundation can be updated though, and I wouldn't say Bootstrap offers flexbox grids yet since it's still alpha, but as soon as it comes out of alpha I'd update it.

**Comment by corysimmons** [comment]
@peterramsing That grid site wouldn't be hard at all. I could design it for you tomorrow if you want to maintain it.

Once it's out there and being linked to, people from all walks will let you know what features their favorite grid supports in comments so it's not like you'd have to track down all the facts, and Lost's current README table is a decent start for that kinda stuff.

**Comment by peterramsing** [comment]
@corysimmons I'm up for anything.

**Comment by peterramsing** [comment]
This has now been resolved with https://github.com/peterramsing/lost/commit/8464f1e81efd86c18db20247773a6c1a3211387f.

@corysimmons Just let me know if you get coding on it a separate table.

**Comment by corysimmons** [comment]
I don't want to maintain it, but I'd be happy to whip something together and transfer it over to you if you'd like. You'd need to get a domain for it.

Oh, and I don't pay for Adobe CC (so expensive...) anymore so I don't have Illustrator. Someone else would have to come up with a logo for it. :^(

**Comment by peterramsing** [comment]
I can handle the domain, etc. I could see if I could either whip a logo up or my wife could.

There should probably be a name for it, I suppose.

**Comment by corysimmons** [comment]
It'll be your project so you can do all the branding and stuff. Something simple and descriptive like "Grid Comparison Table" or something would probably work best.

**Comment by peterramsing** [comment]
I'll ponder for a bit. :smile:
