### ISSUE TITLE
Code examples along side http://corysimmons.github.io/lost

### ISSUE THREAD

**Issue by lewk07** [peterramsing/lost#202]
I'm kind of new to this stuff, so I hope this isn't frivolous. I'd like to see some more examples. The core documentation is kind of abstract. It's like div 1-5 and then you do x. I'd like to see how each of the examples on http://corysimmons.github.io/lost are written.

**Comment by lewk07** [comment]
It would still be nice to see slightly more robust documentation (I'm not certain where else I would make a suggestion like this). Between gulp, elixir, stylus, postcss and all the plugins I had something was wrong somewhere that was causing me issues. Certain things were just not working. It made me feel like I could not grasp the concepts.

**Comment by lewk07** [comment]
https://github.com/corysimmons/lost/tree/gh-pages

Also just found this. Didn't notice it before.

**Comment by peterramsing** [comment]
@lewk07 I totally get how you feel. Front-end dev, especially, has so many plugins and they all move really fast. Where the problem actually is typically takes a long time to find.

There are going to be some new docs coming soon that should really help make Lost more accessible.

If I might give a little time as you said you're new to this stuff.

> Understand how the tools work and not just what tools to use. Nothing is better than maintainable vanilla CSS. Start there and add when you can't maintain DRY code. Feel free to ask questions and I'll be happy to do my best to answer. :smile:
