### ISSUE TITLE
Transferring repo

### ISSUE THREAD

**Issue by corysimmons** [peterramsing/lost#203]
Hey guys,

I love this project, but don't have a lot of time to maintain it right now. I'm working on a new project (not a grid, not on GitHub).

@peterramsing has been the most active contributor and seems to have a good grasp on Lost so I'm going to transfer the repo to him. I'll keep a semi-updated fork so if he goes crazy or something it'll be safe, but I highly doubt it, he seems like a pretty cool dude.

Thanks for making the project so popular and validating my existence as an open source contributor. Can't wait to see what you guys do with it!

**Comment by peterramsing** [comment]
:+1: I'm pretty excited.

**Comment by corysimmons** [comment]
All done. =)

Feel free to update the description of the repo, the README, and whatever else you want.

Thanks Peter! Can't wait to see how it evolves from here.

**Comment by peterramsing** [comment]
It's an honor. I hope to do well by it.
