### ISSUE TITLE
Update Lost on npm to reflect the transfer or repo

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#209]
@corysimmons Might need an assist here.
- [x] Give Peter Access to npm
- [x] Update npm to reflect transfer

**Comment by corysimmons** [comment]
Yeah I need to add you to npm.

**Comment by peterramsing** [comment]
Do you need anything from me?

**Comment by corysimmons** [comment]
Added you as owner of the Lost npm package.
