### ISSUE TITLE
Allow for parameter order to not matter

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#213]
See #181 and #192 where this is discussed a bit more.

This could either be a global change or slowly integrated in. Discussion to be had here.

**Comment by corysimmons** [comment]
It'd be nice if it was a global change. I saw some other PR integrating this for a single property and it'd seemed weird that it was the only property that worked like that...

**Comment by peterramsing** [comment]
I think it might trickle into a few rules, especially in 6.7.x, but would be defined as a feature in 7.0.0.

**Comment by corysimmons** [comment]
:+1:

**Comment by jack-guy** [comment]
+1 This was 100% my fault in not reading the documentation thoroughly first, but specifying `lost-column` with the fraction and a custom gutter not working almost made me stop using lost. I'm glad I didn't, but I think this would be a very helpful feature as far as accessibility is concerned.
