### ISSUE TITLE
Add a lost: reset rule

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#217]
This is spurred from #211 where @alex-ketch suggested this might be an idea.

This issue is to discuss this and what it might affect.

**Comment by corysimmons** [comment]
I'd add `lost-column: reset` and just have it set every single thing that `lost-column` sets back to browser defaults. That should solve whatever issues anyone is having with it.

**Comment by peterramsing** [comment]
Per #211, this is going to be on hold for now. To revisit at a later time.
