### ISSUE TITLE
Create separate docs site and update all documentation

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#224]
I believe that it is time to get some more comprehensive docs and to the majority of it out of the README. I'm still looking into the best way to do this. Any thoughts on frameworks or options. I'm slightly opposed to the Wiki in leu of something like [Neat's docs](http://thoughtbot.github.io/neat-docs/latest/).

**More updates to come to this issue.**

**Comment by mindreframer** [comment]
static documentation generation: 

  Daux: 
    http://daux.io/
    http://daux.io/Features

  Readme.io
    https://readme.io/ (free for OSS) 

  Also you might take inspiration from living styleguides: 
     - http://styleguides.io/ (plenty of articles, pick only few...)

Cheers!

**Comment by peterramsing** [comment]
@mindreframer Awesome links. Thanks!

**Comment by corysimmons** [comment]
Sucks that readme.io cost money. Added "Create open-source/free themeable doc generator" to my todo list...

**Comment by peterramsing** [comment]
[readme.io](https://readme.io) doesn't have to cost: https://readme.readme.io/docs/open-source

**Comment by corysimmons** [comment]
Oh! Hid that down there didn't they?

Nice! *crosses that off his list*

**Comment by mindreframer** [comment]
Had also to look twice there, hehe... )):

Am 5. Januar 2016, um 00:35, Cory Simmons notifications@github.com schrieb:

Oh! Hid that down there didn't they?

Nice! _crosses that off his list_

**Comment by sdale-fevo** [comment]
Great to hear. Understanding the diff use cases of what syntax, goes with what will be really helpful
Like:
--- float vs flexbox
--- global vs inline vars
--- what's optional, what's required, what's default

The Neat docs are a good example, but the complexity of a grid always comes from trying to figure out what are diff techniques to make "your" layout, beyond the documentation examples. Bc of this, coupling these docs with tiny, simple Codepens, I think would really go a long way. 

The model I see here is the way the Greensock folks do it. 
An example, of their [docs](http://greensock.com/docs/#/HTML5/GSAP/TimelineMax/)
They push every [post on their forums](http://greensock.com/forums/topic/13507-svg-plugin-demonstrating-weird-behavior-when-animations-play-in-navigation-bar/) to have a Codepen, and this really helps isolate issues, understand pieces of the whole, and build complexity iteratively.

Here are 4 I created today:

[Codepen: Lost: centered, flex](http://codepen.io/sdale/pen/obwvjm)
[Codepen: Lost: centered, flex - offset](http://codepen.io/sdale/pen/eJROGK)
[Codepen: Lost: centered, flex - offset, with custom overlay](http://codepen.io/sdale/pen/RrgbJW)
[Codepen: Lost: centered, float](http://codepen.io/sdale/pen/mVwbPb?editors=110)

I'll post more as I go..

#2cents

=: s
ps1. the [Level up](https://www.youtube.com/watch?v=IbCYftX5HSU) videos were helpful too
ps2: this is assuming that [Codepen + PostCss play nicely](https://github.com/peterramsing/lost/issues/231)

**Comment by corysimmons** [comment]
Jeffrey Way made Laracasts.com with Lost and did a tutorial on it: https://laracasts.com/series/modern-css-workflow/episodes/2

It'd be nice to keep a Wiki of these CodePens, video tutorials, etc. at least until there is an official site or something (just to start rounding them up).

**Comment by janwirth** [comment]
I think it makes sense to use a stylesheet that is forked from github's. Everyone is used to reading the code and text here so it would be good for the sake of consistency.

A more complex wiki / docs software makes sense in terms of navigation and information retrieval, but consider that a world-writable wiki would decrease the threshold for people that want to contribute :)

A hybrid solution might be considerable aswell.

**Comment by peterramsing** [comment]
@sdale-fevo A bit late in responding, but those are great! Those will certainly be captured in documentation.

@FranzSkuffka Good thoughts. Will definitely consider that!

**Comment by corysimmons** [comment]
Anyone working on this? If not, I have some bandwidth next week.

**Comment by peterramsing** [comment]
@corysimmons Are you still thinking of working on the website?

I did get an account on [Readme.io](https://readme.io/) approved for Open Source. I think that I'd like to start working on that for documentation of the API. I can give you access to that if you'd like.

Also, @corysimmons Are you still thinking of making a project for that grid-comparison? We could put that in the Lost Grid organization.

**Comment by corysimmons** [comment]
I'd prefer to avoid readme.io just because I'd want a better theme than what they offer, and I'm not sure how they store docs. They aren't very clear about what features their open source plan includes, and to that point, I don't see a reason in letting any system tie down our docs in any way, shape, or form.

readme.io and projects like it are cool if you're too busy/lazy to make real docs, but I'm pretty motivated right now so I can get to this next week.

Our docs would be in neat markdown so they'd be super easy to maintain.

Give me next week to make it. If I don't get around to it, or my offering is garbage, then I'm happy to use readme.io.

**Comment by peterramsing** [comment]
Per @corysimmons and I's quick email conversation about this: I'm all for that. Readme.io was just an option among many! I like the idea of a Jekyll solution as you mentioned in the email. I wouldn't say I'm too lazy/busy just wanting to make the right decision. Readme.io does look to be a way to make really great docs but keeping it all in the project is very appealing as well.

**Comment by corysimmons** [comment]
Actually @peterramsing I think I'm gonna get out of your hair over here and work on some other things. I'll be around to help out people in Issues and with anything else you might need.

Feel free to implement the readme.io docs. I think they'll look great and work wonderfully. =)

**Comment by peterramsing** [comment]
Closing for https://github.com/lostgrid/lostgrid-site
