### ISSUE TITLE
Is Lost production ready?

### ISSUE THREAD

**Issue by janhartmann** [peterramsing/lost#228]
Hi,

I've been lurking a lot on Lost lately. Currently writing a bigger application in the health sector and I would like to switch out my currently grid system, Jeet. 

My question is if Lost is production ready, and the polyfills like html5shiv.js, respond.js, border-box is enough for IE8 and upwards? 

I assume there is "no problems" in FF, Chrome etc.

Thanks a lot!
Jan

**Comment by corysimmons** [comment]
Yup. Lost is being used on laracasts.com right now and probably some other big sites I'm unaware of.

And yup, it's IE8+ as long as you use the correct polyfills and such. I've compiled most of them here: https://github.com/corysimmons/boy

Boy still needs a few tweaks here and there and the libraries all need updated, but you can get a good idea from it (or even use it and PR to fix any little issues you run into).

**Comment by janhartmann** [comment]
Sure thing, thanks a lot. Just finished setting up Lost with Gulp, Sass, Autoprefixer and source maps.

Going to play around with it, and if I run into something I'll let you guys know. :)

**Comment by corysimmons** [comment]
Awesome. Hope you like it. :^)

**Comment by peterramsing** [comment]
@janhartmann Certainly let us know if you run into anything. Being the web, there are always things that can be improved upon and I'm trying to get a long-term support roadmap in place to ensure patches, etc are supported into the future even if the main trunk progresses. Feel free to follow [@lostgrid](https://twitter.com/lostgrid) as I'll be posting there on versions, features, etc.

**Comment by corysimmons** [comment]
Cool Twitter bro! :dancers:

**Comment by peterramsing** [comment]
@janhartmann Just wanted to follow up and see if you ended up using LostGrid and if you had any feedback on it. Thanks!

**Comment by janhartmann** [comment]
Hi Peter

Yes I've used it on multiple production sites. Right now I am planning on writing a React Component wrapper for it, as React is my go-to library for apps these days! :-)

**Comment by corysimmons** [comment]
@janhartmann Neat. I'd be interested to see your implementation or work with you on it.

I [tinkered](https://github.com/corysimmons/grid.js) with a really minimalist version of idea but have wanted to revisit it and make it really sweet.

I'd suggest leaning towards that masonry-type markup only. This makes components actually pluggable.

**Comment by janhartmann** [comment]
Sounds very cool, @corysimmons - somewhat along the lines of the markup I am thinking of! :-)

I'll work on the prototype and post a repo link when I get to it! :-)

**Comment by peterramsing** [comment]
@janhartmann Great to hear. Possible reference to #396 for note.

**Comment by BarryThePenguin** [comment]
I know https://collection.maas.museum is using `lost` in production. There was a presentation at React Sydney a couple of months ago about it. Their presentation is on [github](https://github.com/unkleho/react-sydney-meetup-2017)

**Comment by corysimmons** [comment]
Nice! @peterramsing What ever happened to that issue about what was built with Lost? Maybe reopen it? Maybe also have a Showcase on the website? I'm sure lots of people are using it for really cool sites they'd like to show off.

**Comment by peterramsing** [comment]
@corysimmons https://github.com/lostgrid/lostgrid-site/issues/6
