### ISSUE TITLE
Codepen Not Updating?

### ISSUE THREAD

**Issue by sdale-fevo** [peterramsing/lost#231]
Hi,

Getting some weirdness. Not sure where the problem is.
I'm playing around with Lost Grid on Codepen.
I'm trying to understand the differences and effects of float vs flexbox.

I started in Chrome, with a flexbox grid, then converted that to float : http://codepen.io/sdale/pen/mVwbPb?editors=110

First, in attached screencap video, you can see by adding, removing whitespace, the layout breaks?

I then noticed the `.quarter` and `.half` classes still have/set to use Flexbox, which is weird, because I've saved and opened the URL in FFx, Safari, after have converted the layout to float based.. 

There is no flex mentioned anywhere in the source now..
Are you seeing this? 

Curious if you've experienced any of this in your Codepen experiments

![screen shot 2016-01-10 at 2 18 48 pm]

![screen shot 2016-01-10 at 2 52 15 pm](https://cloud.githubusercontent.com/assets/16121654/12223605/23dbd3c0-b7aa-11e5-9b38-a8b652b52031.png)

![screen shot 2016-01-10 at 2 52 00 pm](https://cloud.githubusercontent.com/assets/16121654/12223606/23dd03f8-b7aa-11e5-848c-d0ef64389234.png)

(https://cloud.githubusercontent.com/assets/16121654/12223425/173df4cc-b7a5-11e5-819e-fdbd4482317d.png)

[codepen-lost-1.zip](https://github.com/peterramsing/lost/files/85131/codepen-lost-1.zip)

=: steven

**Comment by sdale-fevo** [comment]
Also, the layout itself is now broken, not sure why - before it was working.. 
hmm

**Comment by peterramsing** [comment]
@sdale-fevo Since taking over Lost I haven't checked into the CodePen integration. **I'll look into this.**

@corysimmons Any thoughts as I've not dealt with a plug in with CodePen?

**Comment by corysimmons** [comment]
Seems like CodePen is just hanging. Tinker around with formatting (fixed it for me). Drop `.quarter` and `.half` rules down to their own lines and properly indent everything (what nerd told you 1 declaration blocks get their own line anyway?).

``` css
.eww { wwww: wwww; }

.ahhh {
  thats: better;
}
```

**Comment by corysimmons** [comment]
I think this can be closed. I haven't experienced anything like this when using proper indentation on CodePen. I think it's probably just a glitch in their massive frontend JS codebase. Let us know if you encounter something like this in PostCSS (even if it is one liners).

**Comment by peterramsing** [comment]
This might be a CodePen issue but I do want to see if there is something that needs updating. Thanks for pointing this out @sdale-fevo. I'll see if I can get some testing time in early this week.

**Comment by peterramsing** [comment]
Regarding the one liner declarations. Before we had all these fancy CSS compression tools in our builds I remember many one-liners. They do get a bit hairy when the codebase grows so they might not be best practice as much. But back in the day they were all over. If a codebase is older than 4 years I'd bet you they are in there. :smile:

**Comment by corysimmons** [comment]
Not my codebases. I always write perfect code. 👀

**Comment by peterramsing** [comment]
This issue is getting a bit stale. If you'd like to bring this issue back up please feel free to reach out.
