### ISSUE TITLE
Support with crosswalk-project

### ISSUE THREAD

**Issue by edriang** [peterramsing/lost#232]
I wanted to know compatibility / support of lost grid used with crosswalk browser.

This browser is mainly used with apache cordova apps, so it would be very interesting to know how well supported is in this platform.

Thanks

**Comment by edriang** [comment]
https://crosswalk-project.org/

**Comment by peterramsing** [comment]
@edriang I haven't used it but will look into it. Thanks for the question!

**Comment by edriang** [comment]
@peterramsing thanks for your reply. I couldn't wait and have tested lost-gh-pages demo page examples, and everything looked great!, So I think that cordova with crosswalk is a good target for lost grid to ensure same functionalities across different platforms!! Let me know if you do some more advanced tests with lostgrid and cordova.

**Comment by corysimmons** [comment]
Awesome! :D

**Comment by corysimmons** [comment]
Seems like it works. Closeable imo

**Comment by peterramsing** [comment]
That sounds promising @edriang. I'm going to leave this issue open for now as a reminder to process how Lost should say it supports libraries like this.
