### ISSUE TITLE
fallback to Flexbox when calc is not supported on Android

### ISSUE THREAD

**Issue by afaayerhan** [peterramsing/lost#234]
this is basically a question. can one just do a build time step to have compilation of multiple stylesheet to serve it based on user agent. so if calc is not supported will just change grid system to use flexbox. would it be just @lost flexbox flex; ?

**Comment by corysimmons** [comment]
Lost won't even work in Flexbox without calc. View compiled: http://codepen.io/corysimmons/pen/bErLxe?editors=010

I'm also not sure how we'd have a build time step to compile it based off of what user agent someone else is using.

Theoretically we could make it so you could set a setting in Lost like `@lost old-android true;` and it'd compile percentage based columns/gutters. But at that point, you might as well just use one of the non-fixed gutter grids like:
- https://jeet.gs/
- http://neat.bourbon.io/
- http://susy.oddbird.net/

**Comment by peterramsing** [comment]
I'm with @corysimmons on this one. I think that this is a bit outside of the scope of Lost.

Are you needing to support IE 8 and old versions of Android? [Caniuse for reference](http://caniuse.com/#search=calc)

I'm always a fan of finding the right tool and one of those other grids might be the more suitable option as opposed to Lost. If this does need to be a feature let's chat, though!

**Comment by corysimmons** [comment]
@afaayerhan Theoretically, you could have a Gulp task that compiled 2 stylesheets. One without flexbox, the other with flexbox.

Then use Modernizr to detect calc support.

If no calc support, then load the flexbox stylesheet.

``` html
<script>
  if (Modernizr.csscalc) {
    document.write('<link rel="stylesheet" href="css/dist/lost-with-calc.css">');
  } else {
    document.write('<link rel="stylesheet" href="css/dist/lost-without-calc.css">');
  }
</script>
```

I haven't tested this but I'm pretty sure it'd work.

**Comment by custa1200** [comment]
## Surely flexbox is not available on any browser that doesn’t support calc?

Mark Johnston

**Comment by corysimmons** [comment]
- http://caniuse.com/#feat=flexbox
- http://caniuse.com/#feat=calc

In particular, old android. That Modernizr solution should work though.

**Comment by custa1200** [comment]
Says it's old flexbox which I assume is not supported by lost anyways?

**Comment by corysimmons** [comment]
Old flexbox is supported. Autoprefixer makes flexbox syntaxes a worry of the past.

**Comment by afaayerhan** [comment]
thanks. @corysimmons would go with the modernizr solution.
