### ISSUE TITLE
Setup a standard way to write Lost with Linting/Documentation

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#237]
Open for discussion but I think this would be a great direction to help ensure the maintainability of the codebase.

[StandardJS](https://github.com/feross/standard)

**Comment by corysimmons** [comment]
Let's do it. :^)

/discussion

**Comment by peterramsing** [comment]
Ps: thanks for the recommendation @adrianca

**Comment by wyze** [comment]
In case you are a fan of semicolons, there is [Semistandard](https://github.com/Flet/semistandard).

Lost is currently using semicolons, so I thought I would just toss this out there.

**Comment by corysimmons** [comment]
Wtf Standardjs doesn't support semi-colons? Why add that in by default? Ugh, I'll research this a bit but I'm so used to semi-colons and pretty sure everyone else in the world is. This might be one of those better-but-unnecessary changes that just throws everyone off a bit. :\

**Comment by corysimmons** [comment]
After about 20 mins of research, https://github.com/twbs/bootstrap/issues/3057#issuecomment-5137415 kinda sums up my feelings on this.

This semi-colonless business got me thinking about how much I like Python and Stylus though...

Anyone else think CoffeeScript is a good idea (I'd love to learn it) or would we be closing the door on a lot of potential contributors? Is CoffeeScript even a thing anymore? It seems like there are a million articles about how vanilla JS is better.

**Comment by wyze** [comment]
CoffeeScript would be closing the door on potential contributors. I believe it is on it's way out. It was all the rage a few years ago but now ES2015 (ES6) is the new rage and has gained a bunch of steam over the past year due to Babel.

**Comment by peterramsing** [comment]
I'm not stuck on any tool in particular. I personally am a fan of the `;` but am more of a fan of standards. I don't think that CoffeeScript is the right direction and I'm not sure if ES2015 is where Lost should go just yet.

I think that @adrianca makes a good point about having a standard. I've noticed that different parts of Lost are written in different ways and I'd love to make Lost easier to contribute to by having a standard way that it is written. I was intending on adding `.eslint` to help with this in the future anyway–maybe that's where this starts along with some more documentation on how Lost is/should be written.

I'll adjust this issue to address the conversation about standardizing Lost for future development.

**Comment by adrian2x** [comment]
I also agree that CoffeeScript is on its way out. It's not standard, not well adopted, not everyone knows it... ES6 is the new standard, and moreover, JS will have a new update every year! So in terms of support, and adopting new features, ES6 seems like the way to go! Since **lost** runs on top of node, the latest version could use whatever ES6 features have been implemented by default on latest [LTS](https://github.com/nodejs/LTS/) version of node. Previous versions could just use ES5 as usual.

**Semistandard** looks great too. I didn't know about this one but I'm leaning more towards preserving semicolons to allow for more people to be able to contribute to the project, as I believe far more people are used to semicolons.

**Comment by corysimmons** [comment]
Okay I'll forget CoffeeScript (my indentation! :sob:) and start familiarizing myself with ES6.

@adrianca rule about matching Lost's ES6 with LTS Node's ES6 features seems pretty sound.

I vote for Semistandard and Node-friendly ES6.

**Comment by peterramsing** [comment]
:+1:  to @corysimmons

**Comment by corysimmons** [comment]
@wyze @adrianca Happen to know of any particularly good resources to learn ES6?

**Comment by adrian2x** [comment]
@corysimmons This is a good one to get started http://es6-features.org/#Constants

**Comment by wyze** [comment]
@corysimmons I learned from the Babel website. But, this seems to have a ton of stuff though: https://github.com/ericdouglas/ES6-Learning

As always, you can DM me on Twitter for questions or help. :)

**Comment by corysimmons** [comment]
Thanks guys! :D

@wyze I don't have Twitter anymore. I'm trying to unplug from the matrix. :neckbeard:

**Comment by gausie** [comment]
Personally I'm a big fan of using eslint with [airbnb's ruleset](https://github.com/airbnb/javascript).

**Comment by peterramsing** [comment]
Closing with #324
