### ISSUE TITLE
Moving Lost to LostGrid organization

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#238]
@corysimmons transitioned this repo to me last month to maintain and since then I've created an [organization](https://github.com/lostgrid). As this is a community project and not a personal project this project should probably move to that organization but before moving the repo a second time in as many months I wanted to get feedback from the community. 

**Any objections?**
**Any thoughts?**
**Any concerns?**

cc: @corysimmons @wyze

**Comment by corysimmons** [comment]
As long as it's the final move I think it's alright to move it one more time.

I think it's good for branding purposes and gives us a place to organize all of our Lost-related projects (syntax highlighters, website, various sample integrations, etc.).

/$.02

**Comment by wyze** [comment]
I think it would be a good move as long as there is more than just the grid that lives under the org.

You already have one project under there and Cory suggested a few more that can be added, so I say go for it.

**Comment by peterramsing** [comment]
@wyze Are you saying I can't put my new Grid called **Found** there? :wink:

I'll probably do this over the weekend pending any blocking comments.

**Comment by corysimmons** [comment]
Soooooo I have a question. I'm thinking of reworking Typographic and making an **insanely awesome UI kit to end all UI kits**. All of these tools would play really nicely together.

Anyone interested in making a more abstract organization name to put all this stuff in? Or should we just keep it all separate?

**Comment by peterramsing** [comment]
I'm down for making it more global.

**Comment by corysimmons** [comment]
Something like what these dudes do https://github.com/at-import except maybe our theme be PostCSS?

http://github.com/postup is avail?

**Comment by peterramsing** [comment]
In laying in bed sick these last few days I've pondered this a bit. I think I'm going to leave Lost in my name for the time being and move it over at a point release.

Regarding the organization name, I'm thinking _something like_  **Lost Tools** might be cool, letting **Lost** be the foundation of that. Possible addons could be:
- Lost Advanced Grid
- Lost Typographic
- Lost UI
- Lost PostCSS Starter Kit
- Lost Fill In the Blank

So, that being said, before I move Lost **I want to have a larger brand strategy realized** along with at least a three person team (or adviser "committee") in place.

That being said, **Lost** is a great name. I think that the only word in question is the second. Ideas below:
1. Lost Code
2. Lost Tools
3. Lost Kit
4. Lost (make suggests)

**Comment by custa1200** [comment]
## Could always call the entity “Flight815”, the flight that was at the centre of the TV series Lost :)

Mark Johnston

**Comment by peterramsing** [comment]
@custa1200 I've actually never seen the show but really like that idea. (a bit of an aviation nerd)

I think that I would like to keep the word "Lost" in it for branding but I like that direction. Anything aviation will get me excited!

**Comment by corysimmons** [comment]
I dunno about branding everything as "Lost". Lost is pretty heavily associated with the grid itself and would overshadow any other tools.

Lost Typographic, etc., just sound weird to me. Maybe I'm too close to the tools to have a good opinion on this.

I think branding everything Lost could work if the organization was primarily focused around the grid:
- github.com/lostgrid/lost
- github.com/lostgrid/atom-support
- github.com/lostgrid/sublime-support
- github.com/lostgrid/lostgrid.org
- etc.

I definitely think there's enough stuff that we could, and perhaps should, make this a "Lost Grid" centric organization instead of a "PostCSS tools" org.

**Comment by peterramsing** [comment]
On my bit of a holiday, I think that I'm a bit more for focusing in on making a powerful grid. Spreading too thin is what will cause lots of holes pop up. I'm going to target this for 7.0.0 so there is a planned transition, and until then it will be under my name.

**Comment by corysimmons** [comment]
Good plan!

**Comment by halvves** [comment]
Not that my opinion is worth much, but I do like @corysimmons's idea of having 'post' in the name. Postup was a good one. Some other suggestions could be (in no order): postpeople (alliteration), postkit, the daily post (ok, now i'm falling apart) etc... (personally fond of postkit).

**Comment by corysimmons** [comment]
Tbh, I'd just leave it here and close this issue. Peter is doing a good job with it and he deserves the name recognition for his efforts.

I also think we should stop naming projects after the tools they're built on. What if a shiny new processor comes out and we want to abandon PostCSS?

This also means I think the whole `postcss-lost` convention is a mistake.

**Comment by peterramsing** [comment]
@corysimmons Aww shucks. Thanks! ...yeah, I haven't put much effort in this because it is a pain for the users.

Okay, closing. I'll also setup a new Gitter if it's staying here, then. 😄 

#274 #265
