### ISSUE TITLE
Calc() function not rendering correctly for certain IE versions

### ISSUE THREAD

**Issue by tellaho** [peterramsing/lost#242]
Using lost-column leads to a broken layout for IE 9,10, and 11. It appears that the columns are too wide and force the last element to break to the next row.

**Here's a comparison of what it looks like in IE 9-11 vs Chrome:**
![image](https://cloud.githubusercontent.com/assets/5141111/12439819/640978cc-bed9-11e5-981f-a95aac36c840.png)
For clarification before it comes up, the row spans across this space. The grid/map element is `position: absolute;` to sit up there.
![image](https://cloud.githubusercontent.com/assets/5141111/12440017/6bc767a2-bedb-11e5-9142-6dd1cdf7c10c.png)

**HTML:**

```
.basic-form__input
.basic-form__select
.basic-form__select
.basic-form__select
```

**CSS:**

```
.basic-form__input {
  lost-column: 1/3 5;
}
.basic-form__select {
  lost-column: 2/9 5;
}
```

We've noticed a hack that fixes it is to use ever-so-slightly lesser numerators over a proportionate denominator. But for obvious reasons, these fractions are less than ideal. E.g. 

```
.basic-form__input {
  lost-column: 999/3000 5;
}
.basic-form__select {
  lost-column: 1999/9000 5;
}
```

**Comment by tellaho** [comment]
Changed the title since it seemed a bit overzealous at first ;) Appreciate the work you guys have put into this!

**Comment by peterramsing** [comment]
Interesting. I'm guessing another case of the sub-pixel rounding has come into play.

I'm going to look into this but before I do, do me a favor and see if 6.7.0 works a bit better here. https://github.com/peterramsing/lost/tree/6.7.0

Just got off of holiday so need to catch up with everything then I'll look in. Thanks for submitting the issue.

**Comment by corysimmons** [comment]
Seems like cycle is messed up. http://codepen.io/corysimmons/pen/vLpEXG?editors=110

Am I missing something?

**Comment by tellaho** [comment]
Ah! Thanks for doing that pen. It got me to recreate my project in Codepen, seeing that the issue was no longer there, and lots of head scratching.

Then I noticed the lost-column calculation looked **different** between my project and the pen.
![image](https://cloud.githubusercontent.com/assets/5141111/12460800/a7797dc0-bf59-11e5-9809-2d061c4a6cf2.png)

Further, I found that my PostCSS stack included _postcss-cssnext_, which included _postcss-calc_. It turns out that the calc plugin was running within the _lost_ function prior to compilation. In essence, it was rounding the margin in a way that IE thought was no bueno.

Thus, after turning off _postcss-calc_, all is running good. Keep up the good work, gentlemen/women that contribute to this great grid system. :+1:

**Comment by corysimmons** [comment]
Thanks. Yeah postcss-calc isn't particularly complete for every scenario. ~~It's unfortunate that CodePen is adding in postcss-cssnext by default... I guess they're trying to let everyone experience that "PostCSS is FuTuRe CsS" meme.~~

~~I'll email their support about it since it seems silly to randomly pick a PostCSS plugin to allow...~~

**Edit** I'm an idiot. You said cssnext was in _your_ stack. I read that as it was in CodePen's stack. Nevermind. :^)

**Comment by corysimmons** [comment]
@taylorkmho Do you happen to have the code you were originally using and the output? As well as the new code and output? It'd be nice if we could open an issue at postcss-calc about fixing this as I'm sure a lot of people are trying to combine cssnext and Lost and banging their head against the wall.

**Comment by tellaho** [comment]
Sure @corysimmons, here's a [pen](http://codepen.io/tellaho/pen/YwYGNw) showing it in action.

A solution I've come across since a couple days ago was to include _lost_ after _cssnext_ (more specifically, _postcss-calc_). You can even see the code change work out in the pen.

**HTML:**

```
.homes
  -for (var i=0;i<12;i++)
    .home
      h2 HOME BLOCK
```

**CSS (pre-compiled):**

```
.homes {
  lost-utility: clearfix;
}

.home {
  lost-column: 1/3 3;
  margin-bottom: 1rem;
  background-color: #eee;
  color: #ccc;
  text-align: center;
}
```

**CSS (compiled):**

```
.blocks {
  *zoom: 1;
}

.blocks:before {
  content: '';
  display: table;
}

.blocks:after {
  content: '';
  display: table;
  clear: both;
}

.block {
  width: calc(99.99% * 1/3 - 0.66667rem);
  margin-bottom: 16px;
  margin-bottom: 1rem;
  background-color: #eee;
  color: #ccc;
  text-align: center;
}

.block:nth-child(n) {
  float: left;
  margin-right: 16px;
  margin-right: 1rem;
  clear: none;
}

.block:last-child {
  margin-right: 0;
}

.block:nth-child(3n) {
  margin-right: 0;
}

.block:nth-child(3n + 1) {
  clear: left;
}
```

**Comment by corysimmons** [comment]
@taylorkmho Thanks. Is it possible to use https://github.com/postcss/postcss-calc#precision-default-5 to fix this in IE?

`precision: 2` seems to work.
