### ISSUE TITLE
Issue when adding a border to elements with lost.

### ISSUE THREAD

**Issue by ghost** [peterramsing/lost#244]
I believe the issue comes from the extra pixels added from border which forces the last element to the next row.

------------------HTML-------------------------
'<section class="row">
        <div class="quarter">1</div>
        <div class="half">2</div>
        <div class="quarter">3</div>
</section>'

--------------------CSS--------------------------
.row {
    width: 100%;
  lost-utility: clearfix;
}
div {
  border: 1px solid black;
}
.quarter {
  lost-column: 1/4 0;
}
.half {
  lost-column: 1/2 0;
}

**Comment by corysimmons** [comment]
In the future when adding code snippets, use the triple backtick (and even the name of the language for syntax highlighting).

```html

<div> foo </div>

```
