### ISSUE TITLE
Issue when adding a border to elements with lost.

### ISSUE THREAD

**Issue by ghost** [peterramsing/lost#245]
I believe the issue comes from the extra pixels added from border which forces the last element to the next row.

------------------HTML-------------------------
`<section class="row">`
`<div class="quarter">1</div>`
`<div class="half">2</div>`
`<div class="quarter">3</div>`
`</section>`

--------------------CSS--------------------------
.row {
    width: 100%;
  lost-utility: clearfix;
}
div {
  border: 1px solid black;
}
.quarter {
  lost-column: 1/4 0;
}
.half {
  lost-column: 1/2 0;
}

**Comment by corysimmons** [comment]
Does this help? http://www.paulirish.com/2012/box-sizing-border-box-ftw/

**Comment by ghost** [comment]
Yes... that's a pretty simple solution.

**Comment by corysimmons** [comment]
I highly suggest you add `* { box-sizing: border-box; }` to your CSS reset to save you a million headaches in the future. =)
