### ISSUE TITLE
lost-offset not working

### ISSUE THREAD

**Issue by gwww** [peterramsing/lost#246]
http://codepen.io/anon/pen/GoQzPd

I'm trying to have the first line as so:
  `<blank> <Heading 1> <Heading 2>`

Perhaps I don't understand offset. Lost 6.7.0; Stylus 0.53.0

Related, I have other questions. Where is the best place to ask?

**Comment by peterramsing** [comment]
@gwww Try `lost-offset: -1/3;`.

See #184 
Let me know if that helps.

---

Regarding the other questions, if they are lost specific, you can always just submit an issue. It sounds like they might not be "issue" related so you're more than welcome to email or tweet.
[lost@peterramsing.com](mailto:lost@peterramsing.com)
[@lostgrid](https://twitter.com/lostgrid)

**Comment by corysimmons** [comment]
@gwww You could also do something slightly shady like http://codepen.io/corysimmons/pen/adqxmR?editors=1100

Adding some sort of `nth-rule` is being discussed for situations like this: https://github.com/peterramsing/lost/issues/239

**Comment by gwww** [comment]
Thank you!

I never would have guessed using -1/3... although did see that after I started looking at the source. From an API perspective, a negative value seems odd to "shift" right.

@corysimmons I considered the shady approach. Yuck :)  I moving stuff from bootstrap where there is too much mixing of style in the html so I'm overly sensitive to hacks right now.

**Comment by peterramsing** [comment]
@gwww This is [changing in 7.0.0](https://github.com/peterramsing/lost/issues/184#issuecomment-174387000) :smile:
