### ISSUE TITLE
Add code used to create demos to the comment above each section

### ISSUE THREAD

**Issue by corysimmons** [peterramsing/lost#247]
It'd take about 10 minutes and would probably help anyone inspecting source on those.

``` html
<!-- Responsive Blocks -->
<!-- lost-column: 1/4; -->
<section>
 ...
```

**Comment by corysimmons** [comment]
If the site's going up soon it might not be worth the effort though? Your call. Feel free to close. Just dropping notes. =)

**Comment by peterramsing** [comment]
Thanks @corysimmons! Closing but it's certainly noted. :smile:

**Comment by corysimmons** [comment]
:+1:
