### ISSUE TITLE
Transition to "cloneAllBefore" to project

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#248]
From @adrianca

This should be added to the entire project...because it's a great way to do this!

https://github.com/adrianca/lost/blob/641a7a13ba5e395169e618b65348d8a9e162f6cf/lib/lost-align.js#L29

``` js
var cloneAllBefore = function(props) {
  for (var prop in props) {
    decl.cloneBefore({prop: prop, value: props[prop]})
  }
};
```

used:

``` js
cloneAllBefore({
  'display': 'initial',
  'display': 'flex',
  'justify-content': 'inherit',
  'align-items': 'inherit'
});
```

**Comment by corysimmons** [comment]
![](https://38.media.tumblr.com/c26b20d3523d58572c00a59fabfc6650/tumblr_mtzmeqC16Z1qcga5ro1_500.gif)

**Comment by peterramsing** [comment]
Closing for #251
