### ISSUE TITLE
Remove the comparison table

### ISSUE THREAD

**Issue by corysimmons** [peterramsing/lost#249]
I put it up without thoroughly examining every other grid.

I studied them all but didn't thoroughly understand their pros and cons. I've been studying them all again lately and know the inner workings of all of the important ones now.

Lost is an opinionated PostCSS grid (works with any preprocessor) that saves most people typing a lot of characters and erases the need for [context](http://susydocs.oddbird.net/en/latest/toolkit/#nested-context), but there are just some things it can't do (asymmetrical grids, generate classes).

The comparison table cherry-picks features and is flat out wrong in multiple spots (e.g. Susy can do masonry; have fixed gutters; etc.).

I'll probably create a new comparison project. With the plethora of grids out there I think people have a right to know what features are available to each of them, but I'm definitely biased, so I'd essentially have to build the backbone of it and then just hope the community would be able suss out a fair balance. To make it more balanced I'll try to get some other grid maintainers involved, but I have my doubts that someone with a weak grid is going to want to help maintain a project that essentially craps all over their grid.

Regardless of whether it takes me a day or year to complete that project, the comparison table should be permanently removed from this project. It's not fair or accurate, and makes me look like what I am: a jerk.

**Comment by corysimmons** [comment]
@peterramsing Thanks =)

**Comment by peterramsing** [comment]
@corysimmons I think that we should still make a tool to help people learn what each grid has to offer. :smile:

**Comment by corysimmons** [comment]
Alrighty, gimme a second

**Comment by corysimmons** [comment]
And by a second I mean 6 hours: https://corysimmons.github.io/compare.gs

I haven't browser tested it other than Chrome and haven't entered any real data, but it seems alright.

Edit these lines to add grids/features:
https://github.com/corysimmons/compare.gs/blob/gh-pages/js/main.js#L3-L15

Still a bit of work to do, but the skeleton is there and it seems pretty good (I'm sure the JS could use tons of refactoring).

**Comment by peterramsing** [comment]
You're a mad man! 💃😀 :+1: 
That looks really cool!
