### ISSUE TITLE
Perdido Grid - a translation of Lost for JSS

### ISSUE THREAD

**Issue by wldcordeiro** [peterramsing/lost#252]
I've been utilizing JSS more and more in projects and wanted to have a grid like Lost available to me, so I translated Lost over, check it out [here](https://www.npmjs.com/package/perdido)

I figured notifying the creators of Lost would be wise. :+1: :smile:

**Comment by corysimmons** [comment]
Very cool! I know a few people have been asking about this! I didn't even know where to start. :+1: :100:

**Comment by peterramsing** [comment]
@wldcordeiro Per our quick chat on Twitter: let's chat about how we might either integrate this into Lost or pair the two so that they remain in line and both benefit from each other. Busy in the office today so I'll circle back on this sometime tomorrow or Friday. Any thoughts welcome.

**Comment by corysimmons** [comment]
I don't know if it's possible to submodule Lost into his fork. They seem like completely different codebases.

(I mean, anything's possible, but seems like it'd be a ton of work)

In the meantime it might be a good idea to keep an [Integrations page](https://github.com/mojotech/jeet/wiki/Jeet-Integrations) on the Wiki just as a reference.

**Comment by corysimmons** [comment]
@wldcordeiro Why "Perdido Grid" instead of something more explicit like "JSS Lost Grid"? I suspect you'll get more users if you go with the latter (as they'll be Googling for `lost grid jss`).

**Comment by wldcordeiro** [comment]
@corysimmons I felt like making a pun while naming it since it's a port/translation so I translated the name to another language. You do make a good point though.

**Comment by wldcordeiro** [comment]
@corysimmons I think the only way to submodule it would be to write out a "lost-core" that only spits out some simple structure that we then manipulate in Lost and Perdido into their preferred returns.

**Comment by corysimmons** [comment]
@wldcordeiro Puns are cool but no one's gonna find it (and there have been people looking for `lost grid jss`) so I might rename it early on if I were you.

I agree that it'd be nice if Lost broke stuff out into `peterramsing/lost-core` or something, but I don't see that happening anytime soon.

I wouldn't get too discouraged, even if Perdido (or whatever you wanna call it) is a few bumps behind Lost, it'll still be a really welcome addition to the JSS ecosystem!

**Comment by wldcordeiro** [comment]
I wanted to test that search @corysimmons so I opened a private window and searched for those keywords. In Google Perdido is the #1 result, in DuckDuckGo, it's #2 after Lost itself, and in Bing it's the same as DuckDuckGo, so it looks like the searches are working. :smiley:

I'll consider changing the name still though if it's a common enough concern (getting that cool npm top level `perdido` name is nice :laughing:)

@peterramsing If you're interested in shooting ideas for `lost-core` sometime just let me know.

P.S. Crazy idea but if we get the `lost-core` down we could make different translations and name them `lost` translated to other languages. :laughing:

**Comment by peterramsing** [comment]
I've been considering what it would look like to create a lost-core since I got the project last month. So, yes, something I have been considering quite a lot and even experimenting with a little behind the scenes.

**Comment by wldcordeiro** [comment]
So Perdido may be having a bit of an API split from Lost (though it may be preempting v7) as I am considering going flexbox default.

The other big consideration I've been having is since Perdido is straight JS changing the row/column fraction arguments to any value between 0 and 1 (with -1 for the reset) the only complications with this is getting the cycling right. This would make things really nice though if you want to do some crazy dynamic grid stuff. :smile: 

This is all happening in the [v2 branch](https://github.com/wldcordeiro/perdido/tree/v2) which will likely come out today (Very quick bump but I had an API change that was BC incompatible and want to follow semver.)

**Comment by peterramsing** [comment]
I think let's just see what happens. I've been hit by the need to ensure a stable piece of software here as I've continued to get feedback and experience myself the ever-changing landscape that is web-development these days. I'd love to see how we could collaborate and build off of each other but it sounds like you have some brilliant ideas and I don't want to hinder your innovation.

That isn't to say that Lost Grid is going to stop innovating–but I am realizing the gravity of the need to build sustainable and long-lasting code. :smile: It's super awesome what you're doing and I'm going to certainly keep up and please don't hesitate to give feedback. Excited to see where this takes us.

Closing for now. :+1:
