### ISSUE TITLE
FlexBox issues in Safari 8

### ISSUE THREAD

**Issue by nelson-rivera** [peterramsing/lost#253]
When I use `lost-flex-container: row;` in a row container it won't work on Safari 8. The reason seems to be that Autoprefixer doesn't change `display: flex` to `display: -webkit-flex`, this version of Safari needs the -webkit prefix to work properly. If besides `lost-flex-container: row;` I add `display: flex` to the same container it works, because Autoprefixer catch the display and adds the prefix. Not sure if caused by some misconfiguration of mine. maybe you've heard this in the past.

**Comment by corysimmons** [comment]
@ai ^

**Comment by peterramsing** [comment]
@nelson-rivera What's your Autoprefixer configuration? Are you specifying support for Safari 8?

**Comment by corysimmons** [comment]
I think this is definitely an Autoprefixer problem.

@nelson-rivera Open an issue there please: https://github.com/postcss/autoprefixer/issues/new

**Comment by ai** [comment]
[Current Autoprefixer](http://autoprefixer.github.io/) adds:

``` css
.example {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

Please always test CSS on online demo before issue report.

**Comment by corysimmons** [comment]
@ai Ah, sorry about that.

Now that I'm re-reading his issue, he just needs to run Autoprefixer after Lost.
@nelson-rivera ^

**Comment by nelson-rivera** [comment]
Thanks @ai and @corysimmons. My bad, running Autoprefixer after lost did the trick.

**Comment by peterramsing** [comment]
:+1: 

@nelson-rivera Let us know if you have any other issues!
