### ISSUE TITLE
Possible dead code?

### ISSUE THREAD

**Issue by wldcordeiro** [peterramsing/lost#254]
I'm almost positive the else blocks to these two are some dead code/unreachable code. I've tried testing for it in Perdido and I ran Lost's test suite and you don't have coverage for it either.

https://github.com/peterramsing/lost/blob/master/lib/lost-offset.js#L74
https://github.com/peterramsing/lost/blob/master/lib/lost-offset.js#L110

**Comment by wldcordeiro** [comment]
Nevermind, idiot me typed something wrong.

**Comment by corysimmons** [comment]
:dancer:
