### ISSUE TITLE
Masonry not working

### ISSUE THREAD

**Issue by fbid** [peterramsing/lost#255]
I was trying to use the Masonry support with no luck. I used the same syntax there is in the documentation here on github.

Example here: http://codepen.io/anon/pen/pgZdxB

**Comment by peterramsing** [comment]
Since taking over lost, masonry testing has been on my to-do list as I haven't done much with it. So, that being said, I don't have any answers right off the top of my head.

I do know that you do need to use a JS library like [Isotope](http://isotope.metafizzy.co/). Could you help me understand a bit more about what isn't working and I'll see what I can do.

**Comment by fbid** [comment]
Sorry for not being so much clear and helpful with my previous post.

I  updated the code in the codepen: http://codepen.io/anon/pen/pgZdxB

This is the issues I found so far doing some tests. I used masonry.js as plugin:
1. Using big gutter values (i.e. 100px) and with a viewport width minor than the main container width, the grid items loose responsiveness and the browser display an horizontal scrollbar in order to let the user see all the content. With default gutter value it works correctly. 
2. Declaring `@lost gutter 100px;` and then removing it makes no changes unless I force the page refresh. It seems that once declared , even if gets removed it remains calculated in the calc() rules. I don't know if it's a real issue or just a codepen related thing.

**Comment by corysimmons** [comment]
Does masonry.js work with Bootstrap with 100px gutters?

Lost's masonry support effectively just uses Lost's math to make Bootstrap markup/grid style.

If masonry.js can't handle Bootstrap's grid then maybe you should find a new masonry plugin?

**Comment by peterramsing** [comment]
Hmm. I'll see if I can get some bandwidth on this this weekend. Work projects abound this week.

**Comment by custa1200** [comment]
I'm running a masonry layout using Isotope and it seems to be working ok.

**Comment by fbid** [comment]
@custa1200  May you post an example of your code?

This is a codepen using Isotope plugin instead of masonry.js: http://codepen.io/anon/pen/OMoJrv

There are the same issues with the horizontal scrollbar and if you resize the preview section to about 650px, you see 1 column instead of two. I hope that helps.

**Comment by custa1200** [comment]
Hey,
Handlebars is:

``` handlebars
<section class="section portfolio-projects">
    {{#each .}}
    <aside class="portfolio-projects__project" data-name="{{striptags title}}" data-end-date="{{formatDate dateEnd "MMMM YYYY"}}">
      <article class="portfolio-projects__project__container">
        <div class="portfolio-projects__project__preview-image">
          <figure class="portfolio-projects__project__preview-image__figure">
            <img class="portfolio-projects__project__preview-image__image" src="/images/project/{{toKebabCase previewImage}}-preview.png" />
          </figure>
        </div>
        <h1 class="portfolio-projects__project__header" >{{{striptags title}}}</h1>
        <div class="portfolio-projects__project__date" data-end-date="{{formatDate dateEnd "MMMM YYYY"}}">{{formatDate dateStart "MMMM YYYY"}} - {{formatDate dateEnd "MMMM YYYY"}}</div>
          <div class="button__row button__row--center">
            <a href="/portfolio/{{{toKebabCase title}}}" class="button">View Project</a>
          </div>
        </article>
    </aside>
    {{/each}}
</section>
```

Stylus is:

``` stylus
.portfolio-projects {
    lost-utility: clearfix;
    lost-masonry-wrap: no-flex;
    margin: $desktop-line-height;

    +below(3) {
        margin: 0 $mobile-line-height;
    }

    &__project {
        lost-masonry-column: 1/4;
        margin-top: 0;
        margin-bottom: $desktop-line-height;

        +below(5) {
            lost-masonry-column: 1/3;
        }

        +below(4) {
            lost-masonry-column: 1/2;
        }

        +below(3) {
            lost-masonry-column: 1/1;
        }

        &__container {
            padding: 0 $desktop-line-height;
            margin: 0;
            background-color: darken($color-grey-lightest, 3%);
            border: 1px solid darken(@background-color, 3%);
            border-radius: $border-radius;
        }

        &__preview-image {
            text-align: center;
            margin: $desktop-line-height 0;

            &__figure {
                width: ($desktop-line-height * 5)
                height: @width;
                border-radius: 50%;
                border: 5px solid $color-white;
                background-color: $color-white;
                overflow: hidden;
                text-align: center;
                padding: 0;
                margin: 0 auto;

            }

            &__image {
                width: 100%;
            }
        }

        &__header {
            font-size: $desktop-font-size-big;
            line-height: $desktop-h3-line-height;
        }

        &__date {
            text-align: center;
            font-size: $desktop-font-size-small;
            text-transform: uppercase;
            margin: 0 0 $desktop-line-height 0;

            +below(2) {
                font-size: $movile-font-size-small;
                margin: $mobile-line-height 0;
            }

        }

        &__intoduction {
            text-align: left;
        }
    }
}
```

My JS for this is:

``` javascript
        var portfolioProjects =$('.portfolio-projects').isotope({
            itemSelector: '.portfolio-projects__project',
            layoutMode: 'masonry',
            getSortData: {
                name: '[data-name]',
                endDate: '[data-end-date]'
            },
            sortBy : 'name'
        });
```

**Comment by corysimmons** [comment]
@peterramsing I know I said I was taking off but the creator of masonry hooked me up with a sweet workaround I thought I'd pass on.

By removing `margin-right` completely from masonry'd elements, masonry plugins will actually pay attention to the `gutter` setting.

http://codepen.io/corysimmons/pen/eJPayv?editors=0110

This means you can probably completely get rid of Lost's support for Bootstrappy markup and dump `lost-masonry-wrap` and `lost-masonry-column` (if you want, might be worth having a discussion with the community).

The only reason I added that stuff was to support masonry but now there's a sweet workaround. Might be worth at least updating documentation.

Alright! Ninja vanish! :dash:

**Comment by fbid** [comment]
@corysimmons  pretty good trick! 

However there's still a problem with media queries. I don't know why but for example adding:

`@media screen and (max-width:700px){
  div{
    lost-column: 1/2;
  }
}`

When applied, the divs have a margin-right equals to the gutter value, so 30px instead of 0.

I solved that adding !important to the margin like this: 
`.masonry-enabled div {
  margin-right: 0 !important;
  clear: none;
}`

**Comment by peterramsing** [comment]
Currently there is a lot of good options but the determination is to find the right one. I don't use masonry very much so I feel slightly inept. I do want to get some time with this.

@fbid is this a dealbreaker issue that needs to be sorted quickly or would you be willing to help out finding the best solution for lasting masonry support for Lost? Thanks for your patience and continued feedback on this issue!

**Comment by fbid** [comment]
You're welcome @peterramsing! It's not a total dealbreaker as the solution provided by @corysimmons is a very good fix, even if it needs a bit of tweaking.

At the moment I'm doing some other tests with lost/masonry and I will provide my feedback in the next few days about some other small issues I encountered.

**Comment by corysimmons** [comment]
I've been fighting with this problem for the past few weeks. Unfortunately, I think the best way for Lost to fully support various layout styles and such is to continue to provide lost-masonry support.

It sucks, but I haven't found another way to dump a random amount of randomly sized blocks into a container without using some negative margin hackery.

It should probably be renamed to something more generic rather than `lost-masonry`. I don't think `lost-bootstrappy-markup` is a great name but that's essentially what it is.
