### ISSUE TITLE
Lost and mobile first approach

### ISSUE THREAD

**Issue by kfrost89** [peterramsing/lost#263]
Initially, I thought there was an issue with globals. See #261. However, it seems there is a bug when using lost and applying a mobile first approach.

Consider the following two examples:

**Not mobile first:**
http://codepen.io/kfrost89/pen/WrWBRZ

**Mobile first:**
http://codepen.io/kfrost89/pen/XXGwKG

Both outputs:
http://pastebin.com/UUwnWCQ0

The two pens should have the same output. However, columns are not equal in height..

EDIT: Updated the first pen.

**Comment by corysimmons** [comment]
Slightly cleaner examples:
- http://codepen.io/corysimmons/pen/PZvmmG?editors=1100 (mobile first with fix)
- http://codepen.io/corysimmons/pen/OMYmmb?editors=1100 (desktop first)

Seems like `lost-column` needs `height: auto; margin-bottom: 0;` added to it.

**Comment by peterramsing** [comment]
Looking into this, I'm tempted to have a `lost-row: none;` rule like we have for [lost-column](https://github.com/peterramsing/lost#lost-column).

**Comment by corysimmons** [comment]
If there is something for column there should be something for row and waffle as well.

**Comment by peterramsing** [comment]
@corysimmons :+1:

**Comment by peterramsing** [comment]
With the the [Darcy Release](https://github.com/peterramsing/lost/releases/tag/v7.0.1), this should be handled with `lost-row: none;`. 👍🏻
