### ISSUE TITLE
Can I use fixed pixel values to define the spacing between the columns?

### ISSUE THREAD

**Issue by mlukaszczyk** [peterramsing/lost#264]
Hey there! Can I use fixed pixel values to define the spacing between the columns? I´m creating an image grid with quadratic tiles. I just want them to have 0px or 10px spacings.

Thanks,

Michael

**Comment by kfrost89** [comment]
I am not quite sure to understand your issue. If you refer to gutter values you can set a global value or use the shorthand syntax:

lost-column: 1/x 0 0;

**Comment by mlukaszczyk** [comment]
Ah thanks! I missunderstood the cycling concept. Now I got it working (: thanks!
