### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by marcustisater** [peterramsing/lost#265]
It would be **awesome** to have an gitter channel for the Lost plugin, I thought there used to be one?

**Comment by kfrost89** [comment]
+1. I would love to see the gitter channel back.

**Comment by peterramsing** [comment]
When the project was transferred to me the channel went away. I've debated a Slack channel but until version 7 when Lost will transition to an organization's repo I wasn't planning on starting up a Gitter again.

There is [@lostgrid](http://twitter.com/lostgrid) on Twitter that I keep an eye on and am working to get a few more core contributors to help manage day-to-day support as my day-job keeps me pretty busy.

I'll be sure to consider setting up another Gitter sooner.

I'll close this for now but feel free to comment with any follow up. Thanks!

**Comment by marcustisater** [comment]
+1 thanks

**Comment by peterramsing** [comment]
@marcustisater https://github.com/peterramsing/lost/issues/238#issuecomment-222809544
