### ISSUE TITLE
nth-child breaks layout on iOS8

### ISSUE THREAD

**Issue by niorad** [peterramsing/lost#270]
I'm using Lost in my current project and it's great so far, except for a few quicks that happen on iOS8/Safari.

After some investigation I came across this Page:
http://stackoverflow.com/questions/26032513/ios8-safari-after-a-pushstate-the-nth-child-selectors-not-works

(This page is also referenced under "known bugs" on CanIUse)

It seems like "nth-of-type" works fine, though. 
I found the nth-of-type issue here, but I didn't find any documentation on how to use/enable it.

Please add some info/warning for users who may need to support iOS8-Versions.

Besides that, everything works fine in all other browsers and it's really convenient to use.
Thanks!

a

**Comment by peterramsing** [comment]
@niorad Thanks for the note. I'm sorry that there weren't any notes on this in the docs.

Would you mind writing a few notes here on what you found specifically or even doing a PR to the `README.md` file. Soon we'll have some new documentation but work has been pretty busy. Time will come soon. :smile:

**Comment by peterramsing** [comment]
This issue is getting a bit stale. If you'd like to bring this issue back up please feel free to reach out.

**Comment by niorad** [comment]
Yes that's fine, I'm sorry. 

If anyone has the same problem:
I managed to fix the issue by using 498/1000 instead of 1/2 on 50/50 grids.

**Comment by peterramsing** [comment]
@niorad Hmm. Odd but I suppose if it works. Have you tried with https://github.com/peterramsing/lost/releases/tag/v7.0.1-beta.2 ?
