### ISSUE TITLE
Option for disabling nth-child styles.

### ISSUE THREAD

**Issue by kyvour** [peterramsing/lost#272]
There are unnecessary styles in some cases when I use only one row of lost-columns or I want to use manual handling for lost properties.

There is the simpliest example: http://codepen.io/kyvour/pen/LNLzpV
What I expect: http://codepen.io/kyvour/pen/ZWyXbw

I think that there should be some additional property/rule (flag true/false) for lost-center, for example lost-center-manual, that will work as lost-cycle and will be disabled by default.

Also in this case there will be need additional rule/property which will show that current column is last.

**Comment by kyvour** [comment]
Definitely Lost is the great grid and it already more powerful than many others, but Lost hasn't enough functionality for manual columns/rows hadling. Now I use Susy / Singularity grid, but in future I want leave sass and use only postcss in my projects. Susy is one thing which stop me do this :)

**Comment by peterramsing** [comment]
Thanks for the notes. Susy is a great grid and I use it in production for work and other things.

Regarding disabling the nth-child styles...I think it's an interesting concept. I'm going to be doing some refactoring of the `lost-column` rule here soon so I'll see what makes sense while I'm doing that.
