### ISSUE TITLE
coming from jeet. is there a similar way to use stack() for lost?

### ISSUE THREAD

**Issue by rlam3** [peterramsing/lost#275]
Is there a similar way to use stack() for lost with rupture, coming over from jeet? 

Or is there a new way you would suggest to do this type of responsive media css.

Also is there an equivalent of edit() from jeet in lost grid?

Thanks!

**Comment by peterramsing** [comment]
To enter the edit mode in LostGrid: `lost-utility: edit;`

For the `stack()` feature from Jeet look into: https://github.com/peterramsing/lost#vertical-grids

**Comment by rlam3** [comment]
If i'm using rupture it would look like this?

``` stylus


div
    lost-column 1/3
    +tablet()
        lost-row 1


```
