### ISSUE TITLE
Looking for a way to use lost without having to use postcss...

### ISSUE THREAD

**Issue by rlam3** [peterramsing/lost#277]
Looking for a way to use lost without having to use postcss...  

Is there a way so we can do something similar to 

```
stylus -u rupture -u axis -u lost -w main.styl??
```

**Comment by peterramsing** [comment]
LostGrid is completely reliant on PostCSS. There are some previous versions from @corysimmons that might still be floating around but currently there are only plans to support LostGrid with PostCSS at the core.

**Comment by rlam3** [comment]
just need to install poststylus

stylus \
    -u ./node_modules/poststylus --with "['lost']" \
        -w css/main.styl -o css/main.css
/

**Comment by peterramsing** [comment]
@rlam3 I haven't seen that. Could you elaborate? 😄

**Comment by EnMod** [comment]
I think s/he's referring to [this](https://github.com/seaneking/poststylus)

**Comment by corysimmons** [comment]
@rlam3 As Peter pointed out, there is no longer a supported Stylus port of Lost. It's entirely PostCSS now (so we don't have to maintain a codebase for 3+ preprocessors).

You can either browse the old commits in this repo until you find a repo snapshot that has the Stylus port, or you can hold tight for a few months while the PostCSS guys iron out a quality CLI and put some finishing touches on SugarSS. Then you will be able to completely replace all preprocessors.

(Sidenote: I feel ya on how annoying PostCSS config can be.)

**Comment by rlam3** [comment]
@corysimmons you can npm install --save-dev poststylus and then use the command above because poststylus is a port for postcss ... this way you can still do it in the commandline instead of using gulp etc.. What is sugarss? it looks similar to stylus....

**Comment by corysimmons** [comment]
@rlam3 Ah that's awesome, thanks for the head's up.

I think SugarSS is what will replace preprocessors for syntax.

**Comment by peterramsing** [comment]
SugarSS looks cool. With all the sites using pre-processors I'm curious what the adoption rate will for sites currently using pre-processors. I know at my company we won't be making any transitions away from pre-processors for a long while. We have too much invested in them. I love all this innovation, though! Can't be mad about that! 😄

**Comment by corysimmons** [comment]
Yeah I think I might try to do the same. I really only used preprocessors for vars and mixins. CSS has vars now. And mixins should probably be parts of PostCSS libs.

Gotta admit I miss the terseness of indentation-based stuff though... :\
