### ISSUE TITLE
Using Packery With Lost

### ISSUE THREAD

**Issue by JakeHenshall** [peterramsing/lost#278]
Hi,

I love lost framework, but the the life of me I cant seem to work out how to get packery working with it.

JS init:

```
        $('.grid').packery({
          // options
            itemSelector: '.grid-item',
            gutter: 10,
            columnWidth: 100,
            percentPosition: true,
            rowHeight: 100

        });
```

CSS:

```
    .grid-item { width: 25%; }
    .grid-item--width2 { width: 50%;}
```

HTML:

```
    <div class="grid">
        <div class="grid-item">{{ post.title }}</div>
    </div>
```

I'm using Timber with WordPress -> https://github.com/timber/timber thats what the {{ post.title }} is.

Here is an example of whats happening.

<img width="1910" alt="mansonry-grid" src="https://cloud.githubusercontent.com/assets/4720782/14591253/bd1d81f2-0505-11e6-9861-08591d0def13.png">

This is basically what i'm trying to achieve. [This](http://themenectar.com/demo/salient-corporate/news/)

If anyone could share some light on this that would be great,

Thanks Jake.

**Comment by peterramsing** [comment]
I haven't ever used Packery. Could you be a bit more specific on the issues your having?

**Comment by JakeHenshall** [comment]
@peterramsing Hey, thanks for responding its all sorted now :)
