### ISSUE TITLE
Nesting media queries in lost columns

### ISSUE THREAD

**Issue by Siva-Siva** [peterramsing/lost#280]
Nesting a media query within a class that has a lost-column property will cause a compilation error.

Example:

```
.column {
  lost-column: 1/12;

  @media (min-width: 1000px) {
    lost-column: 1/6;
  }
}
```

Error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'split' of undefined
```

**Comment by peterramsing** [comment]
@Siva-Siva I'll look into this. Thanks!

**Comment by Siva-Siva** [comment]
Thanks Peter!

**Comment by 412andrewmortimer** [comment]
I've been battling with this in my project as well. Mixins cause this error too.

``` JavaScript
@define-mixin super-good-mixin {
  lost-utility: clearfix;
}
```

`Cannot read property 'split' of undefined`

**Comment by peterramsing** [comment]
@Siva-Siva Are you using a tool that allows the nested syntax like `cssnext`?

**Comment by peterramsing** [comment]
@412andrewmortimer What's the order of compilation that you're doing? Is `LostGrid` before or after you compile that mixin?

**Comment by peterramsing** [comment]
What I think is going on here is that LostGrid is being used before it should be. LostGrid should only be receiving valid css. For example, if a gulpfile looked like this:

```
.pipe(postcss([
  lost(),
  cssnext() 
]))
```

Then there would be a failure because LostGrid doesn't know what to do with the nested syntax.

_But_ if you use LostGrid after like so:

```
.pipe(postcss([
  cssnext(),
  lost()
]))
```

Then you should be able to compile without issue.

**Comment by Siva-Siva** [comment]
@peterramsing Sorry for the late reply. Currently we're using postcss-nested in order to use nested syntax, and looks like it's being used after lost. I'll investigate further to see whether this is root cause.

**Comment by peterramsing** [comment]
@Siva-Siva I would image if you used it before `lost()` then you should be good to go.

**Comment by peterramsing** [comment]
@Siva-Siva Any update on this?
