### ISSUE TITLE
calc within lost-center not working

### ISSUE THREAD

**Issue by dacz** [peterramsing/lost#284]
```
lost-center: calc(var(--soloContentWidth) / 2);
```

Throws an error:

```
ModuleBuildError: Module build failed: CssSyntaxError:… :Unclosed bracket.
```

I use react, cssModules and vars, compiling with webpack.

Am I doing something wrong? Thanks!

**Comment by peterramsing** [comment]
@dacz I think you might be getting a bit to complex for what the `lost-center` rule is looking for. Maybe setting that variable outside of the `lost-center` rule would solve the issue.

There also might be an ordering of what tools are running at what time at play. What's the order that you have your css compiled?

**Comment by dacz** [comment]
Thanks.
I end up with setting this variable, for now.

From webpack loaders:

```
...
{
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader')
      },
...
```

postcss from webpack:

```
postcss: function (webpack) {
    return [
      require('lost'),
      require('postcss-import')({ addDependencyTo: webpack }),
      require('autoprefixer'),
      require('precss')
    ];
  },
```

Thanks for reviewing.

**Comment by dacz** [comment]
@peterramsing You closed this... does this mean that I cannot use calc with lost-center and use somewhere else defined value (that's how I solved it for now but it's not optimal)?

Or is some other solution or I have wrong webpack config?

**Comment by peterramsing** [comment]
@dacz Shucks, I think I read that too quickly. I understood it as you had a solution.

Looking back through this should be able to use the Calc operation within LostGrid. I would recommend moving the LostGrid task the end of your compilation pipeline.

```
postcss: function (webpack) {
    return [
      require('postcss-import')({ addDependencyTo: webpack }),
      require('autoprefixer'),
      require('prices'),
      require('lost')
    ];
  },
```

**Comment by dacz** [comment]
Reordering make it work. Thanks a lot, Peter.
