### ISSUE TITLE
Duplicate Code in lost-column: none

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#285]
Thanks @artisin for this note: https://github.com/peterramsing/lost/pull/211#issuecomment-217240870

From @artisin:

I was looking at the tests and it appears that `lost-column: none;` creates a duplicate of the `a:nth-child(1n)` rule. Based on the code above it looks like that duplicate should be a `a:nth-child(n)` rule.

``` js
it('provides none rule', function() {
  check(
    'a { lost-column: none; }',
    'a { width: auto; }\n' +
    'a:last-child { float: none; clear: none; margin-right: 0; width: auto; }\n' +
    //duplicate, looking at the code above this should be `a:nth-child(n)` ???
    'a:nth-child(1n) { float: none; clear: none; margin-right: 0; width: auto; }\n' +
    'a:nth-child(1n + 1) { float: none; clear: none; margin-right: 0; width: auto; }\n' +
    //duplicate
    'a:nth-child(1n) { float: none; clear: none; margin-right: 0; width: auto; }'
  );
});
```

**Comment by peterramsing** [comment]
@artisin Does #290 resolve this?

**Comment by fetchTe** [comment]
@peterramsing no it does not but I just submitted a pull for #290 should resolve the issue
