### ISSUE TITLE
Setting different column sizes within grid using first/last/nth-child() ?

### ISSUE THREAD

**Issue by alexc101** [peterramsing/lost#301]
Hi,

Here is the set up of my code;

HTML

```
 <section class="grid-two">
            <div class="grid-item-two"></div>
            <div class="grid-item-two"></div>
            <div class="grid-item-two"></div>
        </section>
```

CSS

```
.grid-two {
    lost-utility: clearfix;
    lost-move: 0.85/6;
    lost-column: 5.15/6;
    height: 100%;
}

.grid-item-two  {
    lost-column: 1.75/6;
    background: #2c3e50;
    height: 100px;
    &:first-child {
    }
    &:nth-child(1n){
            lost-column: 2.45/6;
    }
    &:last-child {
    }
}
```

I expect to see;

![Image of Yaktocat](http://i.imgur.com/W9YfPO0.png)

But this is the result;

![Image of Yaktocat](http://i.imgur.com/YacPeRg.png)

I'm wondering why this is?

(Sorry for not tweeting, I don't use twitter as I'm a bit of a dinosaur)

codepen: 

http://codepen.io/alexc101/pen/mEJQaR?editors=110

**Comment by kfrost89** [comment]
Hey there,

See this pen.

http://codepen.io/kfrost89/pen/YWyqmb

**Comment by peterramsing** [comment]
Thanks @kfrost89!

@alexc101 Does that codepen help?

**Comment by kfrost89** [comment]
No worries :+1: 

http://codepen.io/kfrost89/pen/rLOdJZ

This pen uses no-flex. Why does the cycle have to be different?

**Comment by peterramsing** [comment]
This issue is getting a bit stale. If you'd like to bring this issue back up please feel free to reach out.
