### ISSUE TITLE
lost-offset with lost gutter of 0 does not work properly

### ISSUE THREAD

**Issue by i8ramin** [peterramsing/lost#307]
_For support questions you might try tweeting me [@lostgrid](https://twitter.com/lostgrid) first._

---

**Is this a feature request or a bug report?**
bug report

**What is the current behavior?**
`lost-offset` does not behave correctly with gutter of 0

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**

```
@lost flexbox flex;
@lost gutter 0;
```

Then try to use `lost-offset` with a value such as `lost-offset: -1/6`. The offset goes in the wrong direction. If you add any non-zero positive value for gutter, the problem is "fixed".

**What is the behavior that you expect?**
I expect `lost-offset` with gutter of 0 to push and pull in the correction direction. Just like when you have a non-zero gutter value.

**What's the motivation or use-case behind changing the behavior?**
N/A

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
Any of the latest versions of Lost. From `6.8.0` to `7.0.1-2`

**Anything else?**
Codepen to visualize the problem:
http://codepen.io/i8ramin/pen/RRPvVE

**Comment by i8ramin** [comment]
Found out why this was happening. This other postcss plugin was the culprit:
http://cssnext.io/features/#reduced-calc

Just realized that if I pass in the full lost-offset params, like so:
`lost-offset: -1/6 row 0px;`

It works as expected. postcss-next is reducing that `calc` to something that is invalid. So this (valid):
`calc(99.9% * (-0.1 * -1) - (0px - 0px * (-0.1 * -1)) + 0px) !important`

Gets translated into this (invalid):
`calc(99.9% * 0.1 - 0 + 0px) !important`

Interestingly enough, if that `0` were changed into `0px`, it would work just fine. I will open a ticket with the postcss-next about this.

I will leave this open so you can review it and label it, but feel free to close it.

Thank you.

**Comment by peterramsing** [comment]
Thanks for this. I'll tag and close.

**Comment by ericstumper** [comment]
I am having a similar issue with lost 6.8.1. I disabled all other postcss plugins. When using 0px for the gutter everything is working as expected, with a unitless 0 it's not working (both globally set and manually set):

```
lost-offset: -1/23 row 0px;
```

Output:

```
margin-left: calc(99.99% * (-1/23 * -1) - (0px - 0px * (-1/23 * -1)) + 0px) !important;
```

```
lost-offset: -1/23 row 0;
```

Output:

```
margin-left: calc(99.999999% * -1/23) !important;
```

The second obviously results in a negative value pushing the element leftwards out of the grid.

Could anything else besides lost be the cause when all plugins are disabled? I will use 0px for now and disable stylelint for that row.

Would be awesome if you could take another look into this :) Don't know whether this could also be just a CSS calc implementation issue and thus should only be mentioned in the docs.

**Comment by peterramsing** [comment]
@ericstumper I think I may have found the issue and will play with it more this afternoon if I have time.

**Comment by peterramsing** [comment]
Valid CSS syntax is to allow for "0" to work just the same as "0px" so LostGrid should follow this as much as possible.

**Comment by ericstumper** [comment]
I thought so too, only calc(0) I think is invalid for width or something. Thanks a lot for looking into it and all the great work on lost!

**Comment by peterramsing** [comment]
_Note To Self:_ For reading later to make sure that LostGrid won't allow improper syntax.
https://developer.mozilla.org/en-US/docs/Web/CSS/calc#Formal_syntax

**Comment by peterramsing** [comment]
Closing this for #180
