### ISSUE TITLE
Dropping Support for Node v0.10

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#318]
## Drop support for Node v0.10

To use Typescript we're going to need to drop support lest we have failing tests. With Node dropping LTS for 0.10 in October. https://github.com/nodejs/LTS#lts_schedule

Pending feedback we might be able to drop support for this sooner but I want to open this up to discussion. 

(placeholder: will be updated soon)
### ToDo
- #317

**Comment by corysimmons** [comment]
This would need to be a major version bump since it'd break for everyone using Lost <= 0.10, but otherwise 👍

**Comment by peterramsing** [comment]
Closing this as it seems as though this is pretty much all good from users. I've yet to hear anyone say otherwise.

See post here for details: http://peter.coffee/lostgrid-node-versions
