### ISSUE TITLE
--save-dev doesn't save lost to package.json

### ISSUE THREAD

**Issue by JamesTheHacker** [peterramsing/lost#320]
**Is this a feature request or a bug report?**

Bug I believe

**What is the current behavior?**

Running `npm i lost --save-dev` does not add lost to dev. dependencies in `package.json`

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**
1. Run `npm init` to create a new `package.json` file.
2. Run `npm i lost --save-dev`

**What is the behavior that you expect?**

For lost to be added to dev. dependencies in `package.json`

**Comment by peterramsing** [comment]
@JamesTheHacker I can't seem to replicate this. Are you getting any errors?

**Comment by peterramsing** [comment]
This sounds like it might be a local issue. Typically issues like this are not those of the library but of something configured incorrectly.

**Comment by JamesTheHacker** [comment]
Apologies, you were correct. I don't know what happened but when I retried this morning it worked fine.

**Comment by peterramsing** [comment]
@JamesTheHacker Great! Glad to hear.
