### ISSUE TITLE
vw for columns

### ISSUE THREAD

**Issue by ifokeev** [peterramsing/lost#326]
**Is this a feature request or a bug report?**

Feature request

**What is the current behavior?**

Now `lost-column` calculates width based on `%` 

**What is the behavior that you expect?**

I want to set `wv` or `%` based on my layout.
It may be something like `lost-document-column` or an additional attribute for `lost-column`

**What's the motivation or use-case behind changing the behavior?**

Sometimes it is needed to calculate the width based on viewport (wv). Percentage sign is hardcoded and I think it pushes you into the framework very deep. Something may be useful for `lost-row` also.

**Comment by peterramsing** [comment]
Hmm. Certainly something to think about and look into.

I'll put it on my list to see what this might look like and get back to this issue.

**Comment by corysimmons** [comment]
@peterramsing This could be added as a minor-version feature change by adding it as a param to `lost-column`. For instance: `lost-column: 1/3 3 30px vw`.

The only change to the formula would be replacing `%` with `vw`.

https://codepen.io/corysimmons/pen/kkBZyq?editors=1100#0

@ifokeev Could you elaborate on your use case before we add another param to Lost?

**Comment by ifokeev** [comment]
@corysimmons 
for example, I have 3 sections (programmed with Lost) on my site https://monolama.ru/contacts :
1 sidebar, 2 map, 3 contacts. The sidebar and the map are `display: fixed`. I want just make them something like 1/4 vw, 2/4 vw, 1/4 vw.

**Comment by corysimmons** [comment]
@ifokeev Ah, I see. `position: fixed` kinda breaks Lost anyway. We'll definitely discuss appending this param.

In the meantime, since you're not really using gutters (and therefore don't need any complicated math), you can probably just do something like:

``` html
<aside>sidebar</aside>
<main>main</main>
<aside>sidebar 2</aside>
```

``` scss
aside,
main {
  position: fixed;
  overflow-y: auto;
  height: 100vh;
}

aside {
  width: calc(100vw * 3/16);

  &:nth-of-type(2) {
    right: 0;
  }
}

main {
  width: calc(100vw * 10/16);
  left: calc(100vw * 3/16);
}
```

https://codepen.io/corysimmons/pen/WGprLY?editors=1100#0

Lost is great for slapping together grids, but isn't necessarily a 1-stop shop for all layout needs, and can sometimes produce more styles than you need. `calc` is pretty amazing and you can accomplish lots of layouts with it.

Let me know if this helps, and like I said, we'll continue batting around the idea of adding a param for unit selection.

**Comment by peterramsing** [comment]
Looking at this ticket, I think that I'm going to try to make it so that vw/vh could be used anywhere. Still need to rough out exactly how that would look but that's the update. Working on this now.

**Comment by corysimmons** [comment]
More params for the param god!!!

Wait, this could be combined with the rounding param right? Instead of `99.9992423%` he could specify `100vw` (or whatever).

**Comment by peterramsing** [comment]
I was thinking about that...maybe? ...actually very maybe. My first version is just going to have a `lost-unit` param (and then adding a shorthand). I'm just getting the warn to work correctly right now. 👍

**Comment by peterramsing** [comment]
Just hardening the tests for this right now then I'll push it up if you want to see.

**Comment by corysimmons** [comment]
I'm literally passing out and have to wake up in 4.5 hrs, but I dig it. <3

**Comment by peterramsing** [comment]
Closing this for PR: https://github.com/peterramsing/lost/pull/345
