### ISSUE TITLE
Safari clearfix round problem

### ISSUE THREAD

**Issue by komlev** [peterramsing/lost#327]
There is a problem with safari rounding problem while using cleafix, no place for last column. I guess this has something to do with rounding mechanism on safari.
This is the screenshot of that is happening

![lost](https://cloud.githubusercontent.com/assets/513452/18435958/d1f69a6c-78ed-11e6-8381-f5b98243e413.png)

Here is the code itself
https://jsbin.com/hasuxacabi

No ideas yet how to fix this, maybe someone know solution for this?

**Comment by komlev** [comment]
Turns out cleafix is not to be used with flex grids

**Comment by peterramsing** [comment]
@komlev I'm assuming this has been solved then? 👍

**Comment by komlev** [comment]
@peterramsing Yep, removing clearfix did the trick. My only concern is that it might be useful to emphasize this in 'clearfix' section in documentation
