### ISSUE TITLE
1px gap between columns; rounding issue

### ISSUE THREAD

**Issue by x35a** [peterramsing/lost#333]
Hi guys! story about 1px..
Example pen http://codepen.io/ros/pen/qqBJWX
If you can't see a gap this is a pic http://joxi.ru/52aJDoNuGVvMdA
chrome 54, win7 x64, lost v7.0.3
Obviously gap happens when grid width calc is 99.9% or 99.99%. Changing container to 1071px make things okay or changing clac to 99.9999%, but this seems not good idea.
What can you suggest to avoid gap between columns?

**Comment by peterramsing** [comment]
I'm presently not seeing the gap on my machine but I certainly don't doubt that it's there. I'm working on a fix for this in the next version but it's proving to be quite complicated to ensure cross-browser compatibility. When I get to my home office I have a non-retina screen that I'm hoping I can get it to happen so I can debug this more.

**Comment by peterramsing** [comment]
Ahh...okay, I was able to get it so I could see it. I've got some time today that I'm going to focus on trying to fix this. I'm open to suggestions.

**Comment by peterramsing** [comment]
...I'm tempted to just make this a param that allows for the user to either use the default or specify a percentage if they wish. Sometimes 100% width works perfectly in the calc but not all the time if there is nesting. This might be as good a solution as can be shipped now. @corysimmons suggested sometime similar to this In https://github.com/peterramsing/lost/pull/332.

**Comment by x35a** [comment]
Hi Peter! Perhaps I understand why you could not see a gap therefore i've made a liittle change in codepen. Hope it is visible now http://codepen.io/ros/pen/qqBJWX
I've took a look into https://github.com/peterramsing/lost/pull/332 and hope i got your idea about param.
I was trying to show how do i see things, pls take a look http://codepen.io/ros/pen/Wobwrq

**Comment by peterramsing** [comment]
@rosivanov Give this release a try: https://github.com/peterramsing/lost/releases/tag/v8.0.0-beta.1

...you can set a custom percentage with this version with `lost-column-rounder: 100;` and see if that helps.

If you're nesting you'll probably want to stick with the default of 99.9 or you could customize it to make it perfect with `lost-column-rounder: 99.98728372;` (or some other variant).

**Comment by x35a** [comment]
@peterramsing I didn't see `lost-column-rounde`, I will give a try. Seems this is an answer for rounding issues.
Probably you can close this issue, thanks for haelp Peter!

**Comment by peterramsing** [comment]
@rosivanov You wouldn't have seen it before...I [just added](https://github.com/peterramsing/lost/pull/332#commits-pushed-ac5215a) it. 👍
