### ISSUE TITLE
How to write a separate CSS class that adjusts lost-column-gutter for arbitrary grid?

### ISSUE THREAD

**Issue by JeremyBernier** [peterramsing/lost#337]
Is it possible for a CSS class to adjust the gutter for an arbitrary grid fraction?

I want to create a class named `extra-padding` that increases the gutter. The following does not work unless I explicitly add the column fraction into the `extra-padding` class (1/3 in my example), but of course this wouldn't generalize to grids with other fractions (eg. 1/4).

```
.extra-padding {
  lost-column-gutter: 100px;
}


.grid {
  lost-utility: clearfix;

  li {
    lost-column: 1/3 auto 10px;
  }
}

<ul class="grid extra-padding">
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
</ul>
```

I was going to utilize Lost to build my own grid classes, but the inability to do something like this would force me to explore other options :-\

**Comment by peterramsing** [comment]
The nature of how `lost-column-gutter` is computed, it needs a grid fraction to add the gutter in.

https://github.com/peterramsing/lost/blob/master/lib/lost-column.js#L179

**Comment by peterramsing** [comment]
Or I suppose, "How it's used". It's not really computed. That was a pre-lunch response. 👍🏻

**Comment by JeremyBernier** [comment]
Would this be a lot of work to fix?

**Comment by peterramsing** [comment]
I don't think it's a matter of fixing it as much as how would the class that has the new gutter know the context of the grid?

When you use `lost-column: 1/3` it outputs `width: calc(99.99% * 1/3 - (30px - 30px * 1/3));`

If you were to have a class with an adjustment of the gutter to 100 it would have to update that formula with the new gutter of 100 (`width: calc(99.99% * 1/3 - (100px - 100px * 1/3));`).  It can't do that without knowing that there is is the fraction `1/3` there.

You could do it with classes within the `extra-padding` class such as `.extra-padding.one-third` or something along those lines.

---

Hopefully that answers your question. If you feel like this is something that would be worth looking at more and seeing if we could create a solution then I'm open to talking.
