### ISSUE TITLE
Lostgrid website logo cut off on mobile

### ISSUE THREAD

**Issue by tinybike** [peterramsing/lost#348]
The top of the lostgrid logo is cut off on Chrome mobile browser on Android.  Not sure if this is a bug in lostgrid itself but wanted to give you a heads up.

**Comment by tinybike** [comment]
![screenshot_2016-11-24-14-46-34](https://cloud.githubusercontent.com/assets/2637020/20610914/f36afc46-b255-11e6-832e-e272f72279d4.png)

**Comment by peterramsing** [comment]
Thanks for the heads up! I'll take a look.

**Comment by peterramsing** [comment]
Fixed. The issue was caused by the new link. Thanks @tinybike for the find!
