### ISSUE TITLE
Feature request for a visual grid overlay.

### ISSUE THREAD

**Issue by paulca55** [peterramsing/lost#349]
**Is this a feature request or a bug report?**

Feature request for a visual grid overlay.

**What is the current behavior?**

Lost Grid doesn't include this feature as far as I'm aware.

**What is the behavior that you expect?**

Something like the _visual grid_ overlay that **[Bourbon Neat](http://neat.bourbon.io/examples/)** uses. This will make it easier to layout the grid when working with grids in graphics packages such as Sketch. It will also help with troubleshooting the grid too when things aren't lining up properly, etc.

![image](https://cloud.githubusercontent.com/assets/7057526/20703244/e7fbefee-b612-11e6-95d8-946d6c94109d.png)

Many thanks and keep up the good work!

**Comment by peterramsing** [comment]
I'm super stoked to work on this! Any feedback on the syntax for this?

`lost-utility: overlay 12 30px;`

Could possibly even be done automagically with `@lost: overlay 12 30px;` and it would be put on the `html` element by default?

Thoughts?

**Comment by paulca55** [comment]
I'm glad you're happy to implement it :)

I think anything that happens automagically would be cool but I'll leave it in your capable hands on the best way to do this.

It would also be good to be able to change the colour and opacity of the grid overlay too.

I'm excited to see what you can come up with!

**Comment by sidonaldson** [comment]
It would probably need to be inside the body so you can whack up the z-index and overlay it over the whole site,
also adding `pointer-events:none;` so it doesn't prevent clicking.

Maybe a pseudo element with a background gradient?

**Comment by peterramsing** [comment]
@sidonaldson I'd be more than happy to entertain a PR for this if you have some time.

**Comment by sidonaldson** [comment]
@peterramsing I've had a quick go here https://github.com/sidonaldson/lost/tree/overlay (in the utilities)

So far it's harder than I thought as it would have to support multiple types of values, such as rem, em, px so relies heavily on nested calcs. Also the result seems to be quite blurry almost as if the gradient is zoomed in even though it should be pixel perfect. Finally rounding looks to be an issue.

![image](https://cloud.githubusercontent.com/assets/236669/22856904/f5c4c1ea-f092-11e6-92c6-d503f8851b14.png)

**Comment by peterramsing** [comment]
Merged and on `develop`. I'd say we could probably wrap a new version up in a week or two. If you're dying for this let me know and we can put together a beta release earlier.

cc: @ca55ify @sidonaldson
