### ISSUE TITLE
Add visual examples of grid layouts in documentation

### ISSUE THREAD

**Issue by nirfse** [peterramsing/lost#355]
Please consider adding screenshots or visual representation of grid layouts in documentation. There are *horizontal*, *vertical*, *waffles*, and *masonry* grid layouts available to day.

While "horizontal' and "vertical" grids meet the expectations of an accidentally passing by beginner or non front-end developer, it's absolutely not obvious what "waffles" or "masonry" grids look like. I had to double-check in google, what *exactly* is meant by these. But even googling wasn't straightforward with clarification.

**Comment by peterramsing** [comment]
Closing for new issue in proper repo: https://github.com/lostgrid/lostgrid-site/issues/19

**Comment by nirfse** [comment]
@peterramsing oops, sorry for missing proper repo and thanks for transferring.
