### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by bradennapier** [peterramsing/lost#356]
Does this package not have any examples at all?

**Comment by alanaasmaa** [comment]
Thre are docs http://lostgrid.org/ What demo u need ?

**Comment by peterramsing** [comment]
@bradennapier There is a need to add some examples. If there is anything specific I'm more than happy to answer questions.

If you'd like to help: https://github.com/lostgrid/lostgrid-site/issues/14
Here's some examples that might help: https://github.com/lostgrid/lostgrid-episodes

Closing for issue on the docs site: https://github.com/lostgrid/lostgrid-site/issues/14

**Comment by ballPointPenguin** [comment]
I was surprised to look through the readme and docs and not see a single demo or screenshot.
Maybe there is an expectation that people already know what lost-grid is when they see the docs, but for a newcomer trying to make a quick decision "am I interested in this or not?" something visual ANYTHING visual would be very helpful to illustrate what lost-grid can do.

**Comment by alanaasmaa** [comment]
@ballPointPenguin 
There is on part Getting started
Read the docs on LostGrid.org!

**Comment by peterramsing** [comment]
@ballPointPenguin There is this page: something that could be moved to the site. http://peter.coffee/lost/

I could link that over...and I do need to add that to the site as well.

I'm also getting some example projects going to illustrate things a bit better as well. https://github.com/lostgrid/lostgrid-examples
I need to add a lot more.

**Comment by ballPointPenguin** [comment]
Wow Thanks!
Spending about 500 milliseconds checking out http://peter.coffee/lost/ did more for my what-is-this-and-do-I-want-to-use-it query than reading through the docs.
Looks awesome, and super useful.

**Comment by peterramsing** [comment]
Sounds like I really need to link that over. Thanks for the feedback. I'll see if I can get that added soon. Feel free to make a PR for it as well. 👍🏻

**Comment by peterramsing** [comment]
@ballPointPenguin I added a new page to the "real" site: http://lostgrid.org/lostgrid-example.html
