### ISSUE TITLE
Converting project from css/postcss to scss, having issues.

### ISSUE THREAD

**Issue by clevernyyyy** [peterramsing/lost#357]
I did tweet @LostGrid initially because this is more of a support question, but I'm afraid describing it will take longer than 140 characters.

I'm taking a starter project that uses Lost grid and converting from css to scss for some gains.  This is the starter project:  https://github.com/wpioneer/gatsby-starter-lumen

Essentially, I'm converting the project to scss because I much prefer it's structure and would like to move away from all the css files.  For now, I simply:

 * Installed `sass-loader`, `scss`, and `node-sass`
 * Renamed all the css files to scss files
 * And modified `gatsby-node.js` to the following:

```js
var rucksack = require('rucksack-css')
var lost = require("lost")
var cssnext = require("postcss-cssnext")

exports.modifyWebpackConfig = function(config, env) {
    config.merge({
        postcss: [
            lost(),
            rucksack(),
            cssnext({
                browsers: ['>1%', 'last 2 versions']
            })
        ]
    })

    config.loader('svg', {
       test: /\.(svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
       loader: 'file-loader',
    })

    config.loader('sass', {
        test: /\.scss$/,
        loader: 'style-loader!css-loader!sass-loader',
    })

    return config
};
```

Unfortunately, while this does allow me to build and run the project using scss, I've noticed that my sweet Lost grid has disappeared.  After investigation, I notice that `.sidebar` is still reading as `lost-column: 1/3` in the browser (for example), so I can see that the preprocessing which is crucial for Lost grid didn't happen.  

Honestly, this is probably an issue outside of Lost grid, and rather an issue with how I've constructed the `gatsby-node.js`, but I would appreciate any insight into what I'm missing.  I don't mind uploading a *scss/lost starter project for gatsby* once this issue is resolved.

**Comment by peterramsing** [comment]
I'm not entirely sure what's happening and I'm not able to get a full handle on how the stylesheet transpiration is happening with what you included.

You are on the right track, though. From what I can understand: you're not transpiling your SCSS until after you're running PostCSS. If you swap the order, putting the transpiration into SCSS **before** you run your css through PostCSS, you'll see this fixed.

Let me know if you can't get it and I'll take a closer look.

**Comment by clevernyyyy** [comment]
Hmmm, something must be happening low-level, because the solution isn't as simple as swapping these pieces out.

**Comment by peterramsing** [comment]
Hmm. Let me glance at your repo once more...

**Comment by clevernyyyy** [comment]
I can push it somewhere, if you'd like to see mine and not my examples.

**Comment by clevernyyyy** [comment]
Here is my example:  https://github.com/clevernyyyy/hatsec

PS - I'm aware that I accidentally committed `node_modules`, forgot a `.gitignore` in my haste.  Oh well, if I can resolve this, I'll update soon.  Thanks for your help @peterramsing!

**Comment by clevernyyyy** [comment]
Solved.

In `node_modules/gatsby/dist/utils/webpack.config.js`, I changed 

```js
        // CSS modules
        config.loader('cssModules', {
          test: /\.module\.css$/,
          loaders: ['style', cssModulesConfDev, 'postcss']
        });
        config.loader('lessModules', {
          test: /\.module\.less/,
          loaders: ['style', cssModulesConfDev, 'less']
        });
        config.loader('sassModules', {
          test: /\.module\.(sass|scss)/,
          loaders: ['style', cssModulesConfDev, 'sass']
        });
```

to:

```js
        // CSS modules
        config.loader('sassModules', {
          test: /\.module\.(sass|scss)/,
          loaders: ['style', cssModulesConfDev, 'sass']
        });
        config.loader('cssModules', {
          test: /\.module\.css$/,
          loaders: ['style', cssModulesConfDev, 'postcss']
        });
        config.loader('lessModules', {
          test: /\.module\.less/,
          loaders: ['style', cssModulesConfDev, 'less']
        });
```

As suggested.  Thanks for the help!
