### ISSUE TITLE
Error when using webpack 2.2.0

### ISSUE THREAD

**Issue by leesiongchan** [peterramsing/lost#358]
**Is this a feature request or a bug report?**
Bug report

**What is the current behavior?**
Unable to parse files that were previously working fine. 

```
ERROR in ./~/css-loader?{"importLoaders":1,"localIdentName":"[path]_[local]_[hash:base64:5]","modules":true}!./~/postcss-loader??postcss!./src/pages/.../styles.css
Module build failed: TypeError: Cannot read property 'split' of undefined
at appendToSelectors (/Volumes/Personal/Projects/.../node_modules/lost/lib/new-block.js:8:18)
    at newBlock (/Volumes/Personal/Projects/./node_modules/l..ost/lib/new-block.js:15:22)
    at lostWaffleDeclFunction (/Volumes/Personal/Projects/.../node_modules/lost/lib/lost-waffle.js:113:9)
```

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**
1. Upgrade webpack from 2.1 beta to 2.2.0 
2. Fix webpack file
3. Run webpack
4. Failed

**What is the behavior that you expect?**
It should parse the file successfully.

**What's the motivation or use-case behind changing the behavior?**

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
8.0.0

**Anything else?**
Or perhaps this is related to [postcss-loader](https://github.com/postcss/postcss-loader) but not here. Once I comment out `lost` everything seems looking good. It appears that `lost-waffle` causes the error.

**Comment by peterramsing** [comment]
Hmm. Sorry about that. Any chance this project is open source and I could see the source?

**Comment by peterramsing** [comment]
@leesiongchan Any update on whether you can share your config?

**Comment by leesiongchan** [comment]
@peterramsing sorry, I will do it next week.

**Comment by peterramsing** [comment]
Not to push around the blame, but for some reason my gut is saying this might be an issue with Webpack–but I'll get a fresh 2.2 Webpack config and see if LostGrid throws an error on my end. Seeing your config would certainly help, though.

**Comment by leesiongchan** [comment]
```javascript
// Here is the snippet of my webpack config

const webpackConfig = {
...
  module: {
    rules: [{
      include: APP_DIR,
      use: [
        'style-loader',
        { loader: 'css-loader', options: { importLoaders: 1, localIdentName: '[path]_[local]_[hash:base64:5]', modules: true } },
        {
          loader: 'postcss-loader',
          options: {
            ident: 'postcss',
            plugins: function() {
              return [
                require('postcss-import')({
                  path: ['assets/css'],
                  root: APP_DIR,
                }),
                require('postcss-mixins')(),
                require('postcss-conditionals')(),
                require('postcss-simple-vars')(),
                require('postcss-hexrgba')(),
                require('lost')(),
                require('autoprefixer')(),
              ];
            },
          },
        },
      ],
      test: /\.css$/,
    }, ...],
  },
...
};
```

**Comment by leesiongchan** [comment]
Ping @peterramsing

**Comment by peterramsing** [comment]
@leesiongchan Thanks. (was off on holiday–back today, I'll see if I can replicate tonight or Saturday)

**Comment by peterramsing** [comment]
@leesiongchan Just out of curiosity, have you updated to webpack 2.2.1 yet?

**Comment by leesiongchan** [comment]
@peterramsing No. I will try and let you know again.

**Comment by leesiongchan** [comment]
@peterramsing Tested 2.2.1 with no success.

**Comment by peterramsing** [comment]
@leesiongchan Thanks for checking. Sorry I've been silent. Was busy with two conferences these last few weeks and...yeah... something about life?

Would you be up for debugging via Skype? I've got family in Southeast Asia so I'm used to the time difference.

**Comment by leesiongchan** [comment]
@peterramsing Yea, I will open up Skype (ahlee2326) whenever I am available. But afraid I can't help much as I am very much a user didn't really go into the codes to figure out what is happening inside.

**Comment by onehorsetown** [comment]
I had this exact same problem, and it ended up being a boneheaded syntax error in my nested @media tags.   

@leesiongchan -can you share the CSS with the media queries that is causing the issue?     

My CSS is as follows, and it works exactly like I would expect:

```
@import 'common/styles/media';

@lost flexbox flex;

.grid {
  lost-flex-container: row;
}

.card {
  lost-column: 1/1;

  @media (--medium-only) {
    lost-column: 1/3;
  }

  @media (--large-up) {
    lost-column: 1/4;
  }
}
```

My webpack/postcss config is similar to yours, except I am using a bunch of additional plugins.   Like yours, the 'lost' plugin is near to the last one:

```
[
  require('postcss-import')({ ... }),
  require('postcss-custom-properties'),
  require('postcss-calc'),
  require('postcss-simple-vars'),
  require('postcss-custom-media'),
  require('postcss-media-minmax'),
  require('postcss-color-function'),
  require('postcss-nesting'),
  require('postcss-selector-matches'),
  require('postcss-selector-not'),
  require('lost'),
  require('postcss-aspect-ratio'),
  require('autoprefixer')
]
```

lost: version 8.0.0
webpack: version 2.1.1
postcss: 5.2.14

**Comment by peterramsing** [comment]
@leesiongchan I haven't heard back from you in a bit. ...if this is still and issue please comment back but I'm going to close this for now.

**Comment by peterramsing** [comment]
@onehorsetown Thanks for the feedback!

**Comment by robertu7** [comment]
@leesiongchan @onehorsetown @peterramsing

Seem this issue was caused by nesting.

Fixed by this:

```
.card {
  lost-column: 1/1;

  @media (--medium-only) {
     & { lost-column: 1/3; }
  }

  @media (--large-up) {
    & { lost-column: 1/4; }
  }
}

```
