### ISSUE TITLE
Gutter with decimal value issue

### ISSUE THREAD

**Issue by asifshirazi** [peterramsing/lost#367]
Hi,
I expect the output gutter value of `.foo` and `.bar` should be same but if I add gutter decimal value without leading zero, then the output gutter value will set to default gutter.
You can also check this [pen](https://codepen.io/shirazi/pen/NjvmBa).

```
.foo{ lost-column: 1/4 0 0.5em; }
.bar{ lost-column: 3/4 0 .5em; }
```

**Comment by peterramsing** [comment]
Hmm. Looks like the filter on that needs the leading zero. 👍 Thanks!
