### ISSUE TITLE
Update to PostCSS 6.x

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#369]

**Comment by peterramsing** [comment]
Hehe...so this totally blows up the tests. 😢 I'm going to commit the version update and then see what should be done from there.

**Comment by peterramsing** [comment]
It looks like PostCSS 6.x gets rid of new lines? ...I can fix all the test by removing the `\n` w/in the tests. That doesn't feel like a good fix, though.

https://github.com/postcss/postcss/releases/tag/6.0.0

**Comment by peterramsing** [comment]
I've got to do some "work" work so I'm gonna have to put this down for the weekend. @codebysubtract do you have any ideas about this?

**Comment by steve-holland** [comment]
@peterramsing  - The only thing I could think of was to minify both the output of the PostCSS process and the expected output before they are compared in the tests. As long as whatever we do is done to both sides of the compare, we should be good.

I've used `clean-css` as an example and it seems to works fine. If you want to take a look at my branch [here](https://github.com/codebysubtract/lost/tree/upgrade/postcss), you'll see it in action. I've just updated the `check` function, so minimal changes. It also means if the output from PostCSS changes back in the future, it won't really matter either way. We can also gradually change the tests as we go along if that's something we want to do.

**Comment by peterramsing** [comment]
@codebysubtract That's brilliant! That is probably something we're going to want to do.

I'm curious why this new version of PostCSS is transpiling to minified code...it doesn't seem like that was in the changelog. Maybe I'm missing something. I like your idea to minify, though.

If we're going to be doing some large tests change is there anything else about the tests that we should address?

**Comment by steve-holland** [comment]
@peterramsing Great stuff, I'll do a Pull Request.

I agree, I had a good look through the release notes, and also did some Googling and I could find no mention at all about the output changing format. I was surprised no one else ran into the sort of issue we have here. 

Nothing sticks out as far as other changes needed in the tests as far as I can see at the moment.

**Comment by peterramsing** [comment]
Closed for: #379
