### ISSUE TITLE
Incorrect column widths in Firefox

### ISSUE THREAD

**Issue by sarahemilym** [peterramsing/lost#370]
**Is this a feature request or a bug report?**
Bug report

**What is the current behavior?**

Expected behavior for lost-column not happening in Firefox

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**

.foo { lost-column: 1/3 flex }

Result in chrome:
![image](https://cloud.githubusercontent.com/assets/23199168/26675878/69bdc850-46bd-11e7-9a8e-cca0b1ab6fe7.png)

Result in Firefox:

![image](https://cloud.githubusercontent.com/assets/23199168/26675925/95fc3b68-46bd-11e7-829b-b1ac86b647ba.png)

Issue is solved by taking the calculated width and adding it as a max-width:

.foo { lost-column: 1/3 flex; max-width: calc(99.9% * 1/3 - 20px); } 

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**

8.0.0

**Comment by peterramsing** [comment]
Interesting... Thanks for pointing that out. We'll see what we can do to get this patched soon. 👍

**Comment by miguelcaires** [comment]
To elaborate a bit more on this... 

If you check the codepen below in FF, word wrapping appears to be working correctly.
https://codepen.io/miguelcaires/pen/qjWrOL?editors=1100

The codepen is making use of `lost-waffle` but the issue is exactly the same when using `lost-column`.

I did notice something in the output that I'm not sure to be an expected behaviour.

The compiled styles for `.faqs-grid-block__category` in the codepen are as follows:
```
.faqs-grid-block__category {
    border: 1px solid cyan;
    flex: 0 0 auto;
    width: calc(99.9% * 3/9 - (10px - 10px * 3/9));
    height: calc(99.9% * 3/9 - (10px - 10px * 3/9));
    word-wrap: break-word;
}
```

However, when using gulp to compile the styles:
```
'use strict';

const config         = require('../config');
const gulp           = require('gulp');
const postcss        = require('gulp-postcss');
const browserSync    = require('browser-sync').create();

/**
 * PostCSS plugins
 */
const lost = require('lost');

gulp.task('styles', function () {
    let plugins = [
        lost()
    ];

    return gulp.src(config.styles.filename)
        .pipe(postcss(plugins))
        .pipe(gulp.dest(config.styles.dest))
        .pipe(browserSync.reload({ stream: true }));
});
```

Generates additional / different flex styles that *are* affecting the output in FF. 
```
.faqs-grid-block__category {
    border: 1px solid cyan;
    word-wrap: break-word;
    flex-grow: 0;
    flex-shrink: 0;
    flex-basis: calc(99.9% * 3/9 - (10px - 10px * 3/9));
    width: calc(99.9% * 3/9 - (10px - 10px * 3/9));
    height: calc(99.9% * 3/9 - (10px - 10px * 3/9));
}
```

`flex-basis` appears to be the culprit here. If we change the property value to `auto` as per the codepen output, problem doesn't occur anymore in FF.

Lost was installed via Yarn and is @8.0.0

@peterramsing: Hope this provides additional info and helps you identify the cause of the problem.

**Comment by equinusocio** [comment]
I have no problem here on firefox (with global flex)
https://codepen.io/equinusocio/pen/KqqQym

**Comment by miguelcaires** [comment]
@equinusocio That is exactly the issue. the generated styles on codepen are different to the ones you would get from running a gulp build. 

gulp, using postcss, as posted above, is generating a `flex-basis` property that causes the layout to break

**Comment by peterramsing** [comment]
Looking at this today it looks like the fix should be pretty simple. It also looks like there are ways to improve the syntax for this to follow spec a bit better. 👍 

I'll have a PR for this maybe this afternoon? Gotta go grocery shopping first and do some chores around the house first. 🚗 🥖 🚗 👨‍🍳 🍝 💻

**Comment by peterramsing** [comment]
@miguelcaires There was an issue here before with IE, so I'm gonna do some optimizing and then working on testing this with IE to ensure that there isn't a regression here.

**Comment by peterramsing** [comment]
@miguelcaires How comfortable with pulling [this branch](https://github.com/peterramsing/lost/compare/bugfix/flexbox_issues) down and trying it out? See if it solves the issue for you? (I still need to do more cross browser testing myself...)

**Comment by peterramsing** [comment]
@miguelcaires Any updates?

**Comment by peterramsing** [comment]
Here's that IE issue I want to make sure doesn't cause a regression: https://github.com/peterramsing/lost/issues/329

I've been struggling to replicate the issue that started this thread as well, so now I'm questioning everything. @sarahemilym Could you help give me more the code that you're using?

Regarding CodePen, sadly codepen isn't up to date and that's not something I have control over last I checked (although I need/should re-check that).

There are some syntax wins here but before I really sink more than those first few commits in I want to see if I can replicate the bug.

**Comment by miguelcaires** [comment]
Hi @peterramsing sorry about the delay. I will indeed pull the branch and try it out. Will keep you posted.

**Comment by miguelcaires** [comment]
This change makes the grid work correctly! Thanks for looking into this and sorry for taking so long to come back with a reply.

**Comment by peterramsing** [comment]
Wait...just 'cause that fixed things doesn't mean that it is done. Whoops...gotta slate this for dev.

**Comment by peterramsing** [comment]
Got a fix coming in for this!
