### ISSUE TITLE
calc output optimization

### ISSUE THREAD

**Issue by rmoorman** [peterramsing/lost#371]
Hello @peterramsing,

This issue is following up on an email conversation we had about the lost output.

Currently, the following markup:
~~~~css
div {
  lost-column: 1/3;
}
~~~~

becomes something like this:
~~~~css
div {
  width: calc(99.9% * 1/3 - (30px - 30px * 1/3));
}
~~~~

When cssnano is used on the output for example this gets reduced to
~~~~css
div{width:calc(99.9% * 1/3 - 20px)}
~~~~
which seems a solid and reasonable optimization.
There is also an example repository to be found [over here](https://github.com/rmoorman/lostgrid-cssnano-issue).

Best regards,
Rico Moorman

**Comment by peterramsing** [comment]
Looks like a solid optimization. Thanks for the example repo!

A note to implementer: here's where that work would be done: https://github.com/peterramsing/lost/blob/develop/lib/_lg-logic.js#L12

**Comment by steve-holland** [comment]
@peterramsing I've hopefully got a bit of time free this week, so I'l take a look at implementing this one.

**Comment by peterramsing** [comment]
@codebysubtract Sweeeeet!

**Comment by peterramsing** [comment]
Closing this and we ended up not going through with adding `calc` optimizations to LostGrid. See the PR for more details: https://github.com/peterramsing/lost/pull/393
