### ISSUE TITLE
Using global settings and flex, Lost randomly switched back to floats

### ISSUE THREAD

**Issue by brandondurham** [peterramsing/lost#398]
**Is this a feature request or a bug report?**
Bug report

**What is the current behavior?**
We have this in our base CSS file that gets loaded before all others:
```
@lost gutter 0;
@lost flexbox flex;
@lost cycle 12;
@lost rounder 100;
```
Mind you we’re using Webpack to import. It generally works fine, but occasionally sections of the site (not the entire site) will revert back to using the default float technique. Restarting th app _usually_ takes care of that.

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**
No steps to suggest.

**What is the desired behavior?**
Declaring flex globally should mean all lost-related code uses flex.

**What's the motivation or use-case behind changing the behavior?**
Floats are unpredictable. In several areas of the site they break the layout.

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
v8.2.0
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Yes

**Comment by peterramsing** [comment]
Okay, that's super weird.
🤔 
@brandondurham 
What do you mean when you say "restart" the app? Do you mean rebuild/recompile the app?

If yes to restart meaning rebuild, could you answer the following questions:
* Would you mind sharing your Webpack config (I'm fine if you want to email it if it's private...see my email in bio)?
* Does this happen during a watched build such as during development and you're saving, rebuilding, saving, etc.
* Does this happen when building with CI/CD and you're seeing this after that type of build?
* Does this happen only on one computer?
* What version of Node are you using on your computer or environment this is being built in?
* What version of PostCSS are you using?

---
Those are things I can think of that would help start debugging this.

Thanks for your help!

**Comment by peterramsing** [comment]
@Banandrew bump ^^

**Comment by pcjmfranken** [comment]
Could it be that you're globally importing files in your stylus-loader webpack config?

**Comment by brandondurham** [comment]
Boy, this is no longer happening. Results in flex setup with every build¹ now. I’ll keep an eye on it to see if I can reproduce at any point. I’m working heavily on the portion of the site soon that was affected. I’ll let you know if I see it again.

Sorry for the false alarm.

¹ Yes, I meant stopping the app (node) and restarting/rebuilding via Webpack.

**Comment by peterramsing** [comment]
Glad it's not seeming to be an issue. Please do re-open if you see it happen again!
