### ISSUE TITLE
Would love to see how we can integrate lost into Vue.js and Nuxt.js!

### ISSUE THREAD

**Issue by rlam3** [peterramsing/lost#399]
Would love to see how we can integrate lost into Vue.js and Nuxt.js! Thanks!

**Comment by peterramsing** [comment]
@rlam3, could you talk more about that? What would you like to see exactly?

**Comment by rlam3** [comment]
Nothing. I'm beginning migrations over to CSS-Grid from lost since this is where most frontend is heading towards. Thanks!
