### ISSUE TITLE
Make lost-column and lost-align working together

### ISSUE THREAD

**Issue by bee-interactive** [peterramsing/lost#402]
Hi!

I'm trying to build some columns and align all items inside vertically centered. I have tried some stuffs but nothing works. The grid collapse and everything is put together, in center of my template.. 

Here's a part of my code. I'm using stylus:

```
.media-wrap
    border-bottom: solid 1px #d7d9d8
    padding: 10px 0

    .re-order
        lost-column: 5/10 10 10px
        lost-align: middle

    .description
        lost-column: 2/10 10 10px
        lost-align: middle

    .actions
        lost-column: 3/10 10 10px
        lost-align: middle
```

Any idea? I have seen something with a negative offset but not working here.. Thank you in advance for your time!

**Comment by peterramsing** [comment]
@beeInteractive 

Could you provide: 
1. The `html` that you're using (or something to reference)
2. A screenshot of what you're seeing
3. Notes about what the screenshot should look like (annotations on an image are helpful)

2 and 3 could possibly be solved just by providing the `html`. I typically set things up to test things locally to see if there is something going on.

**Comment by bee-interactive** [comment]
@peterramsing Hi! Thanks for the answer. Here's y bit of the html code I use. I keep it very simple:

```
<ul class="medias-wrap">
    <li>
          <div class="media-wrap">
                <div class="re-order">
                    <div><i class="fa fal fa-arrows"></i></div>
                </div>
                <div class="description">
                    <div class="filename">filename.jpg - 2.5 Mb</div>
                    <div class="file-title"><strong>Title: </strong> File title</div>
                </div>
                <div class="actions">
                    <div class="view">
                        <i class="fa far fa-eye"></i>
                    </div>
                    <div class="edit">
                        <i class="fa fa-pencil-alt"></i>
                    </div>
                    <div class="remove">
                        <i class="fa fa-trash-alt"></i>
                    </div>
                </div>
            </div>
     </li>
</ul>
```

Can this information help?
Thanks in advance!

**Comment by peterramsing** [comment]
@beeInteractive, I'll take a look. I'm a bit buried at work right now so it's going to be a few days but I will get back to you.

**Comment by peterramsing** [comment]
@beeInteractive A couple of things:
1. `lost-align: middle;` isn't valid. `lost-align: center;` is what I think you're looking for (there's an error that throws)
2. What are you trying to have it look like?

I'm going to close this for now but feel free to ping back if you think it needs more conversation.

Thanks!
