### ISSUE TITLE
Add support for hex values and safe defaults for lost-utility: edit {color}

### ISSUE THREAD

**Issue by Lucassifoni** [peterramsing/lost#418]
**Is this a feature request or a bug report?**
# Feature request
Add support for hex values and safe defaults for lost-utility: edit {color}

**What is the current behavior?**
Currently, lost crashes when it encounters a hex string instead of a rgb(n,n,n) value in `lost-utility: edit`.

**What is the desired behavior?**
Support strings like `rgb(n,n,n), rgba(n,n,n,n), #333, #222F, invalid input`

**What's the motivation or use-case behind changing the behavior?**
Some build setups translate rgb values to hex strings for brevity before lost gets the chance to process CSS. This breaks lost-utility: edit with a specified color value.

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
Latest lost on master

**Comment by peterramsing** [comment]
Oh, golly! Nice catch!

Looking at the PR, now.

**Comment by peterramsing** [comment]
Pull Request is in. There is still need for documentation for this so I'll just leave this open to represent that.

**Comment by Lucassifoni** [comment]
Hi Peter ! Thanks for the merge and your comments :-) . I'll try to update the docs and submit a PR. Have a nice day !

**Comment by peterramsing** [comment]
@Lucassifoni, awesome! Thanks!

**Comment by Lucassifoni** [comment]
@peterramsing, I'm closing this issue, just wanted to notify you since #431 has been merged.
