### ISSUE TITLE
So I guess this project is dead (as well)!?

### ISSUE THREAD

**Issue by blaasvaer** [peterramsing/lost#433]
*For support questions you might try tweeting me [@lostgrid](https://twitter.com/lostgrid) first.*

-----

**Is this a feature request or a bug report?**

**What is the current behavior?**

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**

**What is the desired behavior?**

**What's the motivation or use-case behind changing the behavior?**

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**

**Anything else?**

**Comment by peterramsing** [comment]
While there are new browser apis that make LostGrid not required such as CSS Grid or using straight Flex Box, LostGrid still has a place.

If that doesn't answer your question let me know.
