### ISSUE TITLE
Need help... Column with padding

### ISSUE THREAD

**Issue by eddietohier** [peterramsing/lost#441]
how to make column and padding in same div like [http://lostgrid.org/lostgrid-example.html](url) The LostGrid Cycle section, i tried:

aside {
    lost-column: 1/3;
    padding: 15px;
}
article {
    lost-column: 2/3;
    padding: 15px;
}

but UI break, the article block breaking down to next line

**Comment by eddietohier** [comment]
my bad.. i forgot to add border-box

**Comment by peterramsing** [comment]
Super! Glad it was an easy fix.
