### ISSUE TITLE
How I Can Add RTL And LTR Both

### ISSUE THREAD

**Issue by negropop** [peterramsing/lost#442]
hello every body♥☺

i have a problem now in adlinkfly script shorten links

I desing a theme  but i want make it when the visitor Select Arabic lang 

site convert to RTL and if he select English lang Come From LTR 

PLEASE I need ahelp fast ♥

**Comment by peterramsing** [comment]
@negropop this hasn't been implemented yet. See #360 

I'll see if I can get some cycles on it or otherwise advise.
