### ISSUE TITLE
Postcss 8 Upgrade

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#445]
https://evilmartians.com/chronicles/postcss-8-plugin-migration

-----

**Is this a feature request or a bug report?**
Use PostCSS 8 Optimizations 

**What is the current behavior?**
PostCSS v8 as is

**What is the desired behavior?**
No regressions

**What's the motivation or use-case behind changing the behavior?**
Keeping up with life

**Comment by lynzrand** [comment]
Hi, it seems like this repo has been silent for ~10 months. Is the upgrade still being worked on?

**Comment by atomicrobokid** [comment]
@peterramsing any update on this? Angular 12+ uses PostCSS 8.

**Comment by LeoniePhiline** [comment]
Bump?

**Comment by ThornWalli** [comment]
Isn't the solution almost ready? https://github.com/peterramsing/lost/pull/446

**Comment by peterramsing** [comment]
Sorry - been on leave. Let me see where this is and jump back on it.

**Comment by peterramsing** [comment]
@ThornWalli , @LeoniePhiline @atomicrobokid @lynzrand 

I just pushed this to beta (`npm i lost@9.0.0-2`). I'll test it some today but could I get some help doing sanity testing?

Thanks.

**Comment by ThornWalli** [comment]
Hello @peterramsing,

have installed it once and immediately encountered a problem 🙂 

Working with `postcss-preset-env` and this no longer seems to run completely.

(Maybe a similar problem. https://github.com/csstools/postcss-plugins/issues/342)

Created an example repo (https://github.com/ThornWalli/lost-test). 
There the nested media query is not taken over, the lost plugin was added.

**Comment by peterramsing** [comment]
Interesting. I'll work on some failing tests and get it resolved.

**Comment by peterramsing** [comment]
Failing test added
https://github.com/peterramsing/lost/pull/446/files#diff-e0ca830dd683a20c3e2e1351cba319f6c94c7ae0936dbc4f96e4e45866201c05

**Comment by ThornWalli** [comment]
@peterramsing Could it be that the test output is wrong? 🙂

https://github.com/peterramsing/lost/pull/447

**Comment by peterramsing** [comment]
@ThornWalli , @LeoniePhiline @atomicrobokid @lynzrand

@ThornWalli, this has the fix for the media query nesting issue.

New version for test `npm i lost@9.0.0-beta.3`

**Comment by peterramsing** [comment]
@ThornWalli it looks like your test repo works fine with Beta 3.

**Comment by ThornWalli** [comment]
@peterramsing Looks good! 🙂

**Comment by ThornWalli** [comment]
@peterramsing What is the current status here? 🙂

**Comment by peterramsing** [comment]
@ThornWalli, if things are looking good on your end then I think it's safe to do a merge. I've done quite a bit of testing myself, too. I'll go ahead and do it.

**Comment by peterramsing** [comment]
*the merge is already done - just need to release a non-beta version.

**Comment by peterramsing** [comment]
I got pulled away right before I was going to release it (kids needed something). I’m planning to get to it tonight.

**Comment by peterramsing** [comment]
This was done with the latest v9 release
