### ISSUE TITLE
postcss config

### ISSUE THREAD

**Issue by franck-lynn** [peterramsing/lost#457]
_For support questions you might try tweeting me [@lostgrid](https://twitter.com/lostgrid) first._

---

**Is this a feature request or a bug report?**

**What is the current behavior?**

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**

**What is the desired behavior?**

**What's the motivation or use-case behind changing the behavior?**

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**

**Anything else?**

**Comment by peterramsing** [comment]
@franck-lynn , not sure what this is... do you need help with anything?

**Comment by peterramsing** [comment]
closing - if you need anything let me know
