### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by corysimmons** [peterramsing/lost#98]
~~I have a mockup for this already so no help required.~~ Help is definitely required. :X

**Comment by teddybradford** [comment]
Any news on this? I imagine having something like Jeet's website for Lost would do wonders for adoption.

**Comment by AleksejDix** [comment]
i am waiting for it too. make some crazy stuff with it 

and implementing an optional vertical gutter to the .lost-center would be nice too .
people use it alot

**Comment by corysimmons** [comment]
I've got some really nice graphics for it, but I'm struggling with how to put them all together. Originally I was going to make it horizontal scrolling, but that ended up being pretty terrible, so now I'm tinkering around with it.

Starting a new job as well so I don't have a ton of free time to devote to things like this, but I definitely agree about adoption.

To be honest, I've been kinda slacking on this because I wanted to keep getting feedback from the community on Lost and it's syntax before I try to make it super popular. It would let me change API stuff without making a *ton* of people mad.

**Comment by dandv** [comment]
Lost seems even more awesome than [flexboxgrid](https://github.com/kristoferjoseph/flexboxgrid/issues/62) but has only about half the GitHub stars?

**Comment by corysimmons** [comment]
Actually if anyone wants to work on this I'd love to see what you come up with! (I'm super busy nowadays so don't have a lot of time to work on this)

**Comment by juhalehtonen** [comment]
@corysimmons You mentioned "some really nice graphics" in an earlier comment to this issue. Are these something you would like to see being utilized in the Lost website (assuming someone else would get his or her hands dirty on this)?

**Comment by corysimmons** [comment]
@juhalehtonen I have a bunch of vectors of cute characters and such. I was going to do some side scrolling website for it but got super lazy. If you'd like, I could pass these images off to you and you could sprinkle them throughout a design if you're interested in working on a new design (preferably not side scrolling hehe).

**Comment by peterramsing** [comment]
Notes for quick ToDo:
- [ ] Show libraries it works with like Crosswalk-project #232

**Comment by corysimmons** [comment]
Dropping this here https://github.com/tripit/slate

Haven't really looked at it but it looks nice on the outside and seems pretty well maintained.

**Comment by peterramsing** [comment]
Closing for https://github.com/lostgrid/lostgrid-site
